//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Features.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HiraganaToRomaji {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HiraganaToRomaji() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Features.Tools.LinguistResources.HiraganaToRomaji", typeof(HiraganaToRomaji).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a.
        /// </summary>
        internal static string あ {
            get {
                return ResourceManager.GetString("あ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à i.
        /// </summary>
        internal static string い {
            get {
                return ResourceManager.GetString("い", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ye.
        /// </summary>
        internal static string いぇ {
            get {
                return ResourceManager.GetString("いぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à u.
        /// </summary>
        internal static string う {
            get {
                return ResourceManager.GetString("う", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vu.
        /// </summary>
        internal static string ゔ {
            get {
                return ResourceManager.GetString("ゔ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à e.
        /// </summary>
        internal static string え {
            get {
                return ResourceManager.GetString("え", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à o.
        /// </summary>
        internal static string お {
            get {
                return ResourceManager.GetString("お", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ka.
        /// </summary>
        internal static string か {
            get {
                return ResourceManager.GetString("か", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ga.
        /// </summary>
        internal static string が {
            get {
                return ResourceManager.GetString("が", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ki.
        /// </summary>
        internal static string き {
            get {
                return ResourceManager.GetString("き", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gi.
        /// </summary>
        internal static string ぎ {
            get {
                return ResourceManager.GetString("ぎ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kyi.
        /// </summary>
        internal static string きぃ {
            get {
                return ResourceManager.GetString("きぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gyi.
        /// </summary>
        internal static string ぎぃ {
            get {
                return ResourceManager.GetString("ぎぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kye.
        /// </summary>
        internal static string きぇ {
            get {
                return ResourceManager.GetString("きぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gye.
        /// </summary>
        internal static string ぎぇ {
            get {
                return ResourceManager.GetString("ぎぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kya.
        /// </summary>
        internal static string きゃ {
            get {
                return ResourceManager.GetString("きゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gya.
        /// </summary>
        internal static string ぎゃ {
            get {
                return ResourceManager.GetString("ぎゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kyu.
        /// </summary>
        internal static string きゅ {
            get {
                return ResourceManager.GetString("きゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gyu.
        /// </summary>
        internal static string ぎゅ {
            get {
                return ResourceManager.GetString("ぎゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kyo.
        /// </summary>
        internal static string きょ {
            get {
                return ResourceManager.GetString("きょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gyo.
        /// </summary>
        internal static string ぎょ {
            get {
                return ResourceManager.GetString("ぎょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ku.
        /// </summary>
        internal static string く {
            get {
                return ResourceManager.GetString("く", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gu.
        /// </summary>
        internal static string ぐ {
            get {
                return ResourceManager.GetString("ぐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ke.
        /// </summary>
        internal static string け {
            get {
                return ResourceManager.GetString("け", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ge.
        /// </summary>
        internal static string げ {
            get {
                return ResourceManager.GetString("げ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ko.
        /// </summary>
        internal static string こ {
            get {
                return ResourceManager.GetString("こ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à go.
        /// </summary>
        internal static string ご {
            get {
                return ResourceManager.GetString("ご", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sa.
        /// </summary>
        internal static string さ {
            get {
                return ResourceManager.GetString("さ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à za.
        /// </summary>
        internal static string ざ {
            get {
                return ResourceManager.GetString("ざ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shi.
        /// </summary>
        internal static string し {
            get {
                return ResourceManager.GetString("し", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ji.
        /// </summary>
        internal static string じ {
            get {
                return ResourceManager.GetString("じ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ji.
        /// </summary>
        internal static string じぃ {
            get {
                return ResourceManager.GetString("じぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à she.
        /// </summary>
        internal static string しぇ {
            get {
                return ResourceManager.GetString("しぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à je.
        /// </summary>
        internal static string じぇ {
            get {
                return ResourceManager.GetString("じぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sha.
        /// </summary>
        internal static string しゃ {
            get {
                return ResourceManager.GetString("しゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ja.
        /// </summary>
        internal static string じゃ {
            get {
                return ResourceManager.GetString("じゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shu.
        /// </summary>
        internal static string しゅ {
            get {
                return ResourceManager.GetString("しゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ju.
        /// </summary>
        internal static string じゅ {
            get {
                return ResourceManager.GetString("じゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sho.
        /// </summary>
        internal static string しょ {
            get {
                return ResourceManager.GetString("しょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jo.
        /// </summary>
        internal static string じょ {
            get {
                return ResourceManager.GetString("じょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à su.
        /// </summary>
        internal static string す {
            get {
                return ResourceManager.GetString("す", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zu.
        /// </summary>
        internal static string ず {
            get {
                return ResourceManager.GetString("ず", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à se.
        /// </summary>
        internal static string せ {
            get {
                return ResourceManager.GetString("せ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ze.
        /// </summary>
        internal static string ぜ {
            get {
                return ResourceManager.GetString("ぜ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à so.
        /// </summary>
        internal static string そ {
            get {
                return ResourceManager.GetString("そ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zo.
        /// </summary>
        internal static string ぞ {
            get {
                return ResourceManager.GetString("ぞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ta.
        /// </summary>
        internal static string た {
            get {
                return ResourceManager.GetString("た", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à da.
        /// </summary>
        internal static string だ {
            get {
                return ResourceManager.GetString("だ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chi.
        /// </summary>
        internal static string ち {
            get {
                return ResourceManager.GetString("ち", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ji.
        /// </summary>
        internal static string ぢ {
            get {
                return ResourceManager.GetString("ぢ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chi.
        /// </summary>
        internal static string ちぃ {
            get {
                return ResourceManager.GetString("ちぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ji.
        /// </summary>
        internal static string ぢぃ {
            get {
                return ResourceManager.GetString("ぢぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à che.
        /// </summary>
        internal static string ちぇ {
            get {
                return ResourceManager.GetString("ちぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à je.
        /// </summary>
        internal static string ぢぇ {
            get {
                return ResourceManager.GetString("ぢぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cha.
        /// </summary>
        internal static string ちゃ {
            get {
                return ResourceManager.GetString("ちゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ja.
        /// </summary>
        internal static string ぢゃ {
            get {
                return ResourceManager.GetString("ぢゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chu.
        /// </summary>
        internal static string ちゅ {
            get {
                return ResourceManager.GetString("ちゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ju.
        /// </summary>
        internal static string ぢゅ {
            get {
                return ResourceManager.GetString("ぢゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cho.
        /// </summary>
        internal static string ちょ {
            get {
                return ResourceManager.GetString("ちょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jo.
        /// </summary>
        internal static string ぢょ {
            get {
                return ResourceManager.GetString("ぢょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tsu.
        /// </summary>
        internal static string つ {
            get {
                return ResourceManager.GetString("つ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zu.
        /// </summary>
        internal static string づ {
            get {
                return ResourceManager.GetString("づ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à te.
        /// </summary>
        internal static string て {
            get {
                return ResourceManager.GetString("て", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de.
        /// </summary>
        internal static string で {
            get {
                return ResourceManager.GetString("で", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to.
        /// </summary>
        internal static string と {
            get {
                return ResourceManager.GetString("と", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à do.
        /// </summary>
        internal static string ど {
            get {
                return ResourceManager.GetString("ど", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à na.
        /// </summary>
        internal static string な {
            get {
                return ResourceManager.GetString("な", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ni.
        /// </summary>
        internal static string に {
            get {
                return ResourceManager.GetString("に", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nyi.
        /// </summary>
        internal static string にぃ {
            get {
                return ResourceManager.GetString("にぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nye.
        /// </summary>
        internal static string にぇ {
            get {
                return ResourceManager.GetString("にぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nya.
        /// </summary>
        internal static string にゃ {
            get {
                return ResourceManager.GetString("にゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nyu.
        /// </summary>
        internal static string にゅ {
            get {
                return ResourceManager.GetString("にゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nyo.
        /// </summary>
        internal static string にょ {
            get {
                return ResourceManager.GetString("にょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nu.
        /// </summary>
        internal static string ぬ {
            get {
                return ResourceManager.GetString("ぬ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ne.
        /// </summary>
        internal static string ね {
            get {
                return ResourceManager.GetString("ね", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no.
        /// </summary>
        internal static string の {
            get {
                return ResourceManager.GetString("の", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ha.
        /// </summary>
        internal static string は {
            get {
                return ResourceManager.GetString("は", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ba.
        /// </summary>
        internal static string ば {
            get {
                return ResourceManager.GetString("ば", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pa.
        /// </summary>
        internal static string ぱ {
            get {
                return ResourceManager.GetString("ぱ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hi.
        /// </summary>
        internal static string ひ {
            get {
                return ResourceManager.GetString("ひ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bi.
        /// </summary>
        internal static string び {
            get {
                return ResourceManager.GetString("び", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pi.
        /// </summary>
        internal static string ぴ {
            get {
                return ResourceManager.GetString("ぴ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hyi.
        /// </summary>
        internal static string ひぃ {
            get {
                return ResourceManager.GetString("ひぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à byi.
        /// </summary>
        internal static string びぃ {
            get {
                return ResourceManager.GetString("びぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pyi.
        /// </summary>
        internal static string ぴぃ {
            get {
                return ResourceManager.GetString("ぴぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hye.
        /// </summary>
        internal static string ひぇ {
            get {
                return ResourceManager.GetString("ひぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bye.
        /// </summary>
        internal static string びぇ {
            get {
                return ResourceManager.GetString("びぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pye.
        /// </summary>
        internal static string ぴぇ {
            get {
                return ResourceManager.GetString("ぴぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hya.
        /// </summary>
        internal static string ひゃ {
            get {
                return ResourceManager.GetString("ひゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bya.
        /// </summary>
        internal static string びゃ {
            get {
                return ResourceManager.GetString("びゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pya.
        /// </summary>
        internal static string ぴゃ {
            get {
                return ResourceManager.GetString("ぴゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hyu.
        /// </summary>
        internal static string ひゅ {
            get {
                return ResourceManager.GetString("ひゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à byu.
        /// </summary>
        internal static string びゅ {
            get {
                return ResourceManager.GetString("びゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pyu.
        /// </summary>
        internal static string ぴゅ {
            get {
                return ResourceManager.GetString("ぴゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hyo.
        /// </summary>
        internal static string ひょ {
            get {
                return ResourceManager.GetString("ひょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à byo.
        /// </summary>
        internal static string びょ {
            get {
                return ResourceManager.GetString("びょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pyo.
        /// </summary>
        internal static string ぴょ {
            get {
                return ResourceManager.GetString("ぴょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fu.
        /// </summary>
        internal static string ふ {
            get {
                return ResourceManager.GetString("ふ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bu.
        /// </summary>
        internal static string ぶ {
            get {
                return ResourceManager.GetString("ぶ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pu.
        /// </summary>
        internal static string ぷ {
            get {
                return ResourceManager.GetString("ぷ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fa.
        /// </summary>
        internal static string ふぁ {
            get {
                return ResourceManager.GetString("ふぁ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fi.
        /// </summary>
        internal static string ふぃ {
            get {
                return ResourceManager.GetString("ふぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fe.
        /// </summary>
        internal static string ふぇ {
            get {
                return ResourceManager.GetString("ふぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fo.
        /// </summary>
        internal static string ふぉ {
            get {
                return ResourceManager.GetString("ふぉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à he.
        /// </summary>
        internal static string へ {
            get {
                return ResourceManager.GetString("へ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à be.
        /// </summary>
        internal static string べ {
            get {
                return ResourceManager.GetString("べ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pe.
        /// </summary>
        internal static string ぺ {
            get {
                return ResourceManager.GetString("ぺ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ho.
        /// </summary>
        internal static string ほ {
            get {
                return ResourceManager.GetString("ほ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bo.
        /// </summary>
        internal static string ぼ {
            get {
                return ResourceManager.GetString("ぼ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à po.
        /// </summary>
        internal static string ぽ {
            get {
                return ResourceManager.GetString("ぽ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ma.
        /// </summary>
        internal static string ま {
            get {
                return ResourceManager.GetString("ま", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mi.
        /// </summary>
        internal static string み {
            get {
                return ResourceManager.GetString("み", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à myi.
        /// </summary>
        internal static string みぃ {
            get {
                return ResourceManager.GetString("みぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mye.
        /// </summary>
        internal static string みぇ {
            get {
                return ResourceManager.GetString("みぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mya.
        /// </summary>
        internal static string みゃ {
            get {
                return ResourceManager.GetString("みゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à myu.
        /// </summary>
        internal static string みゅ {
            get {
                return ResourceManager.GetString("みゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à myo.
        /// </summary>
        internal static string みょ {
            get {
                return ResourceManager.GetString("みょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mu.
        /// </summary>
        internal static string む {
            get {
                return ResourceManager.GetString("む", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à me.
        /// </summary>
        internal static string め {
            get {
                return ResourceManager.GetString("め", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mo.
        /// </summary>
        internal static string も {
            get {
                return ResourceManager.GetString("も", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ya.
        /// </summary>
        internal static string や {
            get {
                return ResourceManager.GetString("や", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yu.
        /// </summary>
        internal static string ゆ {
            get {
                return ResourceManager.GetString("ゆ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yo.
        /// </summary>
        internal static string よ {
            get {
                return ResourceManager.GetString("よ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ra.
        /// </summary>
        internal static string ら {
            get {
                return ResourceManager.GetString("ら", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ri.
        /// </summary>
        internal static string り {
            get {
                return ResourceManager.GetString("り", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ryi.
        /// </summary>
        internal static string りぃ {
            get {
                return ResourceManager.GetString("りぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rye.
        /// </summary>
        internal static string りぇ {
            get {
                return ResourceManager.GetString("りぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rya.
        /// </summary>
        internal static string りゃ {
            get {
                return ResourceManager.GetString("りゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ryu.
        /// </summary>
        internal static string りゅ {
            get {
                return ResourceManager.GetString("りゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ryo.
        /// </summary>
        internal static string りょ {
            get {
                return ResourceManager.GetString("りょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ru.
        /// </summary>
        internal static string る {
            get {
                return ResourceManager.GetString("る", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à re.
        /// </summary>
        internal static string れ {
            get {
                return ResourceManager.GetString("れ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ro.
        /// </summary>
        internal static string ろ {
            get {
                return ResourceManager.GetString("ろ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wa.
        /// </summary>
        internal static string わ {
            get {
                return ResourceManager.GetString("わ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wi.
        /// </summary>
        internal static string ゐ {
            get {
                return ResourceManager.GetString("ゐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à we.
        /// </summary>
        internal static string ゑ {
            get {
                return ResourceManager.GetString("ゑ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wo.
        /// </summary>
        internal static string を {
            get {
                return ResourceManager.GetString("を", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n.
        /// </summary>
        internal static string ん {
            get {
                return ResourceManager.GetString("ん", resourceCulture);
            }
        }
    }
}
