//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Features.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KatakanaToRomaji {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KatakanaToRomaji() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Features.Tools.LinguistResources.KatakanaToRomaji", typeof(KatakanaToRomaji).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a.
        /// </summary>
        internal static string ア {
            get {
                return ResourceManager.GetString("ア", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à i.
        /// </summary>
        internal static string イ {
            get {
                return ResourceManager.GetString("イ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yi.
        /// </summary>
        internal static string イェ {
            get {
                return ResourceManager.GetString("イェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à u.
        /// </summary>
        internal static string ウ {
            get {
                return ResourceManager.GetString("ウ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vu.
        /// </summary>
        internal static string ヴ {
            get {
                return ResourceManager.GetString("ヴ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à va.
        /// </summary>
        internal static string ヴァ {
            get {
                return ResourceManager.GetString("ヴァ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wi.
        /// </summary>
        internal static string ウィ {
            get {
                return ResourceManager.GetString("ウィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vi.
        /// </summary>
        internal static string ヴィ {
            get {
                return ResourceManager.GetString("ヴィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à we.
        /// </summary>
        internal static string ウェ {
            get {
                return ResourceManager.GetString("ウェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ve.
        /// </summary>
        internal static string ヴェ {
            get {
                return ResourceManager.GetString("ヴェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vo.
        /// </summary>
        internal static string ヴォ {
            get {
                return ResourceManager.GetString("ヴォ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à e.
        /// </summary>
        internal static string エ {
            get {
                return ResourceManager.GetString("エ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à o.
        /// </summary>
        internal static string オ {
            get {
                return ResourceManager.GetString("オ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ka.
        /// </summary>
        internal static string カ {
            get {
                return ResourceManager.GetString("カ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ga.
        /// </summary>
        internal static string ガ {
            get {
                return ResourceManager.GetString("ガ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ki.
        /// </summary>
        internal static string キ {
            get {
                return ResourceManager.GetString("キ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gi.
        /// </summary>
        internal static string ギ {
            get {
                return ResourceManager.GetString("ギ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kyi.
        /// </summary>
        internal static string キィ {
            get {
                return ResourceManager.GetString("キィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gyi.
        /// </summary>
        internal static string ギィ {
            get {
                return ResourceManager.GetString("ギィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kye.
        /// </summary>
        internal static string キェ {
            get {
                return ResourceManager.GetString("キェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gye.
        /// </summary>
        internal static string ギェ {
            get {
                return ResourceManager.GetString("ギェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kya.
        /// </summary>
        internal static string キャ {
            get {
                return ResourceManager.GetString("キャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gya.
        /// </summary>
        internal static string ギャ {
            get {
                return ResourceManager.GetString("ギャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kyu.
        /// </summary>
        internal static string キュ {
            get {
                return ResourceManager.GetString("キュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gyu.
        /// </summary>
        internal static string ギュ {
            get {
                return ResourceManager.GetString("ギュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kyo.
        /// </summary>
        internal static string キョ {
            get {
                return ResourceManager.GetString("キョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gyo.
        /// </summary>
        internal static string ギョ {
            get {
                return ResourceManager.GetString("ギョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ku.
        /// </summary>
        internal static string ク {
            get {
                return ResourceManager.GetString("ク", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gu.
        /// </summary>
        internal static string グ {
            get {
                return ResourceManager.GetString("グ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ke.
        /// </summary>
        internal static string ケ {
            get {
                return ResourceManager.GetString("ケ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ge.
        /// </summary>
        internal static string ゲ {
            get {
                return ResourceManager.GetString("ゲ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ko.
        /// </summary>
        internal static string コ {
            get {
                return ResourceManager.GetString("コ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à go.
        /// </summary>
        internal static string ゴ {
            get {
                return ResourceManager.GetString("ゴ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sa.
        /// </summary>
        internal static string サ {
            get {
                return ResourceManager.GetString("サ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à za.
        /// </summary>
        internal static string ザ {
            get {
                return ResourceManager.GetString("ザ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shi.
        /// </summary>
        internal static string シ {
            get {
                return ResourceManager.GetString("シ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ji.
        /// </summary>
        internal static string ジ {
            get {
                return ResourceManager.GetString("ジ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ji.
        /// </summary>
        internal static string ジィ {
            get {
                return ResourceManager.GetString("ジィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à she.
        /// </summary>
        internal static string シェ {
            get {
                return ResourceManager.GetString("シェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à je.
        /// </summary>
        internal static string ジェ {
            get {
                return ResourceManager.GetString("ジェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sha.
        /// </summary>
        internal static string シャ {
            get {
                return ResourceManager.GetString("シャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ja.
        /// </summary>
        internal static string ジャ {
            get {
                return ResourceManager.GetString("ジャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shu.
        /// </summary>
        internal static string シュ {
            get {
                return ResourceManager.GetString("シュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ju.
        /// </summary>
        internal static string ジュ {
            get {
                return ResourceManager.GetString("ジュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sho.
        /// </summary>
        internal static string ショ {
            get {
                return ResourceManager.GetString("ショ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jo.
        /// </summary>
        internal static string ジョ {
            get {
                return ResourceManager.GetString("ジョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à su.
        /// </summary>
        internal static string ス {
            get {
                return ResourceManager.GetString("ス", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zu.
        /// </summary>
        internal static string ズ {
            get {
                return ResourceManager.GetString("ズ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à se.
        /// </summary>
        internal static string セ {
            get {
                return ResourceManager.GetString("セ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ze.
        /// </summary>
        internal static string ゼ {
            get {
                return ResourceManager.GetString("ゼ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à so.
        /// </summary>
        internal static string ソ {
            get {
                return ResourceManager.GetString("ソ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zo.
        /// </summary>
        internal static string ゾ {
            get {
                return ResourceManager.GetString("ゾ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ta.
        /// </summary>
        internal static string タ {
            get {
                return ResourceManager.GetString("タ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à da.
        /// </summary>
        internal static string ダ {
            get {
                return ResourceManager.GetString("ダ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chi.
        /// </summary>
        internal static string チ {
            get {
                return ResourceManager.GetString("チ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chi.
        /// </summary>
        internal static string チィ {
            get {
                return ResourceManager.GetString("チィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à che.
        /// </summary>
        internal static string チェ {
            get {
                return ResourceManager.GetString("チェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cha.
        /// </summary>
        internal static string チャ {
            get {
                return ResourceManager.GetString("チャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chu.
        /// </summary>
        internal static string チュ {
            get {
                return ResourceManager.GetString("チュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cho.
        /// </summary>
        internal static string チョ {
            get {
                return ResourceManager.GetString("チョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tsu.
        /// </summary>
        internal static string ツ {
            get {
                return ResourceManager.GetString("ツ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zu.
        /// </summary>
        internal static string ヅ {
            get {
                return ResourceManager.GetString("ヅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à te.
        /// </summary>
        internal static string テ {
            get {
                return ResourceManager.GetString("テ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de.
        /// </summary>
        internal static string デ {
            get {
                return ResourceManager.GetString("デ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to.
        /// </summary>
        internal static string ト {
            get {
                return ResourceManager.GetString("ト", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à do.
        /// </summary>
        internal static string ド {
            get {
                return ResourceManager.GetString("ド", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à na.
        /// </summary>
        internal static string ナ {
            get {
                return ResourceManager.GetString("ナ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ni.
        /// </summary>
        internal static string ニ {
            get {
                return ResourceManager.GetString("ニ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nyi.
        /// </summary>
        internal static string ニィ {
            get {
                return ResourceManager.GetString("ニィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nye.
        /// </summary>
        internal static string ニェ {
            get {
                return ResourceManager.GetString("ニェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nya.
        /// </summary>
        internal static string ニャ {
            get {
                return ResourceManager.GetString("ニャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nyu.
        /// </summary>
        internal static string ニュ {
            get {
                return ResourceManager.GetString("ニュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nyo.
        /// </summary>
        internal static string ニョ {
            get {
                return ResourceManager.GetString("ニョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nu.
        /// </summary>
        internal static string ヌ {
            get {
                return ResourceManager.GetString("ヌ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ne.
        /// </summary>
        internal static string ネ {
            get {
                return ResourceManager.GetString("ネ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no.
        /// </summary>
        internal static string ノ {
            get {
                return ResourceManager.GetString("ノ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ha.
        /// </summary>
        internal static string ハ {
            get {
                return ResourceManager.GetString("ハ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ba.
        /// </summary>
        internal static string バ {
            get {
                return ResourceManager.GetString("バ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pa.
        /// </summary>
        internal static string パ {
            get {
                return ResourceManager.GetString("パ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hi.
        /// </summary>
        internal static string ヒ {
            get {
                return ResourceManager.GetString("ヒ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bi.
        /// </summary>
        internal static string ビ {
            get {
                return ResourceManager.GetString("ビ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pi.
        /// </summary>
        internal static string ピ {
            get {
                return ResourceManager.GetString("ピ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hyi.
        /// </summary>
        internal static string ヒィ {
            get {
                return ResourceManager.GetString("ヒィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à byi.
        /// </summary>
        internal static string ビィ {
            get {
                return ResourceManager.GetString("ビィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pyi.
        /// </summary>
        internal static string ピィ {
            get {
                return ResourceManager.GetString("ピィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hye.
        /// </summary>
        internal static string ヒェ {
            get {
                return ResourceManager.GetString("ヒェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bye.
        /// </summary>
        internal static string ビェ {
            get {
                return ResourceManager.GetString("ビェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pye.
        /// </summary>
        internal static string ピェ {
            get {
                return ResourceManager.GetString("ピェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hya.
        /// </summary>
        internal static string ヒャ {
            get {
                return ResourceManager.GetString("ヒャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bya.
        /// </summary>
        internal static string ビャ {
            get {
                return ResourceManager.GetString("ビャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pya.
        /// </summary>
        internal static string ピャ {
            get {
                return ResourceManager.GetString("ピャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hyu.
        /// </summary>
        internal static string ヒュ {
            get {
                return ResourceManager.GetString("ヒュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à byu.
        /// </summary>
        internal static string ビュ {
            get {
                return ResourceManager.GetString("ビュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pyu.
        /// </summary>
        internal static string ピュ {
            get {
                return ResourceManager.GetString("ピュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hyo.
        /// </summary>
        internal static string ヒョ {
            get {
                return ResourceManager.GetString("ヒョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à byo.
        /// </summary>
        internal static string ビョ {
            get {
                return ResourceManager.GetString("ビョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pyo.
        /// </summary>
        internal static string ピョ {
            get {
                return ResourceManager.GetString("ピョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fu.
        /// </summary>
        internal static string フ {
            get {
                return ResourceManager.GetString("フ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bu.
        /// </summary>
        internal static string ブ {
            get {
                return ResourceManager.GetString("ブ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pu.
        /// </summary>
        internal static string プ {
            get {
                return ResourceManager.GetString("プ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fa.
        /// </summary>
        internal static string ファ {
            get {
                return ResourceManager.GetString("ファ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fi.
        /// </summary>
        internal static string フィ {
            get {
                return ResourceManager.GetString("フィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fe.
        /// </summary>
        internal static string フェ {
            get {
                return ResourceManager.GetString("フェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fo.
        /// </summary>
        internal static string フォ {
            get {
                return ResourceManager.GetString("フォ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à he.
        /// </summary>
        internal static string ヘ {
            get {
                return ResourceManager.GetString("ヘ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à be.
        /// </summary>
        internal static string ベ {
            get {
                return ResourceManager.GetString("ベ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pe.
        /// </summary>
        internal static string ペ {
            get {
                return ResourceManager.GetString("ペ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ho.
        /// </summary>
        internal static string ホ {
            get {
                return ResourceManager.GetString("ホ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bo.
        /// </summary>
        internal static string ボ {
            get {
                return ResourceManager.GetString("ボ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à po.
        /// </summary>
        internal static string ポ {
            get {
                return ResourceManager.GetString("ポ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ma.
        /// </summary>
        internal static string マ {
            get {
                return ResourceManager.GetString("マ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mi.
        /// </summary>
        internal static string ミ {
            get {
                return ResourceManager.GetString("ミ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à myi.
        /// </summary>
        internal static string ミィ {
            get {
                return ResourceManager.GetString("ミィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mye.
        /// </summary>
        internal static string ミェ {
            get {
                return ResourceManager.GetString("ミェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mya.
        /// </summary>
        internal static string ミャ {
            get {
                return ResourceManager.GetString("ミャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à myu.
        /// </summary>
        internal static string ミュ {
            get {
                return ResourceManager.GetString("ミュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à myo.
        /// </summary>
        internal static string ミョ {
            get {
                return ResourceManager.GetString("ミョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mu.
        /// </summary>
        internal static string ム {
            get {
                return ResourceManager.GetString("ム", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à me.
        /// </summary>
        internal static string メ {
            get {
                return ResourceManager.GetString("メ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mo.
        /// </summary>
        internal static string モ {
            get {
                return ResourceManager.GetString("モ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ya.
        /// </summary>
        internal static string ヤ {
            get {
                return ResourceManager.GetString("ヤ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yu.
        /// </summary>
        internal static string ユ {
            get {
                return ResourceManager.GetString("ユ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yo.
        /// </summary>
        internal static string ヨ {
            get {
                return ResourceManager.GetString("ヨ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ra.
        /// </summary>
        internal static string ラ {
            get {
                return ResourceManager.GetString("ラ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ri.
        /// </summary>
        internal static string リ {
            get {
                return ResourceManager.GetString("リ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ryi.
        /// </summary>
        internal static string リィ {
            get {
                return ResourceManager.GetString("リィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rye.
        /// </summary>
        internal static string リェ {
            get {
                return ResourceManager.GetString("リェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rya.
        /// </summary>
        internal static string リャ {
            get {
                return ResourceManager.GetString("リャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ryu.
        /// </summary>
        internal static string リュ {
            get {
                return ResourceManager.GetString("リュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ryo.
        /// </summary>
        internal static string リョ {
            get {
                return ResourceManager.GetString("リョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ru.
        /// </summary>
        internal static string ル {
            get {
                return ResourceManager.GetString("ル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à re.
        /// </summary>
        internal static string レ {
            get {
                return ResourceManager.GetString("レ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ro.
        /// </summary>
        internal static string ロ {
            get {
                return ResourceManager.GetString("ロ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wa.
        /// </summary>
        internal static string ワ {
            get {
                return ResourceManager.GetString("ワ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wo.
        /// </summary>
        internal static string ヲ {
            get {
                return ResourceManager.GetString("ヲ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n.
        /// </summary>
        internal static string ン {
            get {
                return ResourceManager.GetString("ン", resourceCulture);
            }
        }
    }
}
