//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Features.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KatakanaToRomaji {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KatakanaToRomaji() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Features.Tools.LinguistResources.KatakanaToRomaji", typeof(KatakanaToRomaji).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string ア {
            get {
                return ResourceManager.GetString("ア", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string イ {
            get {
                return ResourceManager.GetString("イ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yi.
        /// </summary>
        internal static string イェ {
            get {
                return ResourceManager.GetString("イェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        internal static string ウ {
            get {
                return ResourceManager.GetString("ウ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vu.
        /// </summary>
        internal static string ヴ {
            get {
                return ResourceManager.GetString("ヴ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to va.
        /// </summary>
        internal static string ヴァ {
            get {
                return ResourceManager.GetString("ヴァ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wi.
        /// </summary>
        internal static string ウィ {
            get {
                return ResourceManager.GetString("ウィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        internal static string ヴィ {
            get {
                return ResourceManager.GetString("ヴィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we.
        /// </summary>
        internal static string ウェ {
            get {
                return ResourceManager.GetString("ウェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve.
        /// </summary>
        internal static string ヴェ {
            get {
                return ResourceManager.GetString("ヴェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vo.
        /// </summary>
        internal static string ヴォ {
            get {
                return ResourceManager.GetString("ヴォ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        internal static string エ {
            get {
                return ResourceManager.GetString("エ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string オ {
            get {
                return ResourceManager.GetString("オ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka.
        /// </summary>
        internal static string カ {
            get {
                return ResourceManager.GetString("カ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ga.
        /// </summary>
        internal static string ガ {
            get {
                return ResourceManager.GetString("ガ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ki.
        /// </summary>
        internal static string キ {
            get {
                return ResourceManager.GetString("キ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gi.
        /// </summary>
        internal static string ギ {
            get {
                return ResourceManager.GetString("ギ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyi.
        /// </summary>
        internal static string キィ {
            get {
                return ResourceManager.GetString("キィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gyi.
        /// </summary>
        internal static string ギィ {
            get {
                return ResourceManager.GetString("ギィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kye.
        /// </summary>
        internal static string キェ {
            get {
                return ResourceManager.GetString("キェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gye.
        /// </summary>
        internal static string ギェ {
            get {
                return ResourceManager.GetString("ギェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kya.
        /// </summary>
        internal static string キャ {
            get {
                return ResourceManager.GetString("キャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gya.
        /// </summary>
        internal static string ギャ {
            get {
                return ResourceManager.GetString("ギャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyu.
        /// </summary>
        internal static string キュ {
            get {
                return ResourceManager.GetString("キュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gyu.
        /// </summary>
        internal static string ギュ {
            get {
                return ResourceManager.GetString("ギュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyo.
        /// </summary>
        internal static string キョ {
            get {
                return ResourceManager.GetString("キョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gyo.
        /// </summary>
        internal static string ギョ {
            get {
                return ResourceManager.GetString("ギョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ku.
        /// </summary>
        internal static string ク {
            get {
                return ResourceManager.GetString("ク", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gu.
        /// </summary>
        internal static string グ {
            get {
                return ResourceManager.GetString("グ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ke.
        /// </summary>
        internal static string ケ {
            get {
                return ResourceManager.GetString("ケ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ge.
        /// </summary>
        internal static string ゲ {
            get {
                return ResourceManager.GetString("ゲ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.
        /// </summary>
        internal static string コ {
            get {
                return ResourceManager.GetString("コ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        internal static string ゴ {
            get {
                return ResourceManager.GetString("ゴ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string サ {
            get {
                return ResourceManager.GetString("サ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za.
        /// </summary>
        internal static string ザ {
            get {
                return ResourceManager.GetString("ザ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shi.
        /// </summary>
        internal static string シ {
            get {
                return ResourceManager.GetString("シ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ji.
        /// </summary>
        internal static string ジ {
            get {
                return ResourceManager.GetString("ジ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ji.
        /// </summary>
        internal static string ジィ {
            get {
                return ResourceManager.GetString("ジィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to she.
        /// </summary>
        internal static string シェ {
            get {
                return ResourceManager.GetString("シェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je.
        /// </summary>
        internal static string ジェ {
            get {
                return ResourceManager.GetString("ジェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha.
        /// </summary>
        internal static string シャ {
            get {
                return ResourceManager.GetString("シャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string ジャ {
            get {
                return ResourceManager.GetString("ジャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shu.
        /// </summary>
        internal static string シュ {
            get {
                return ResourceManager.GetString("シュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ju.
        /// </summary>
        internal static string ジュ {
            get {
                return ResourceManager.GetString("ジュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sho.
        /// </summary>
        internal static string ショ {
            get {
                return ResourceManager.GetString("ショ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jo.
        /// </summary>
        internal static string ジョ {
            get {
                return ResourceManager.GetString("ジョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to su.
        /// </summary>
        internal static string ス {
            get {
                return ResourceManager.GetString("ス", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zu.
        /// </summary>
        internal static string ズ {
            get {
                return ResourceManager.GetString("ズ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se.
        /// </summary>
        internal static string セ {
            get {
                return ResourceManager.GetString("セ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ze.
        /// </summary>
        internal static string ゼ {
            get {
                return ResourceManager.GetString("ゼ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so.
        /// </summary>
        internal static string ソ {
            get {
                return ResourceManager.GetString("ソ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zo.
        /// </summary>
        internal static string ゾ {
            get {
                return ResourceManager.GetString("ゾ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ta.
        /// </summary>
        internal static string タ {
            get {
                return ResourceManager.GetString("タ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        internal static string ダ {
            get {
                return ResourceManager.GetString("ダ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chi.
        /// </summary>
        internal static string チ {
            get {
                return ResourceManager.GetString("チ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chi.
        /// </summary>
        internal static string チィ {
            get {
                return ResourceManager.GetString("チィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to che.
        /// </summary>
        internal static string チェ {
            get {
                return ResourceManager.GetString("チェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cha.
        /// </summary>
        internal static string チャ {
            get {
                return ResourceManager.GetString("チャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chu.
        /// </summary>
        internal static string チュ {
            get {
                return ResourceManager.GetString("チュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cho.
        /// </summary>
        internal static string チョ {
            get {
                return ResourceManager.GetString("チョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tsu.
        /// </summary>
        internal static string ツ {
            get {
                return ResourceManager.GetString("ツ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zu.
        /// </summary>
        internal static string ヅ {
            get {
                return ResourceManager.GetString("ヅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te.
        /// </summary>
        internal static string テ {
            get {
                return ResourceManager.GetString("テ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string デ {
            get {
                return ResourceManager.GetString("デ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dei.
        /// </summary>
        internal static string ディ {
            get {
                return ResourceManager.GetString("ディ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string ト {
            get {
                return ResourceManager.GetString("ト", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string ド {
            get {
                return ResourceManager.GetString("ド", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to na.
        /// </summary>
        internal static string ナ {
            get {
                return ResourceManager.GetString("ナ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ni.
        /// </summary>
        internal static string ニ {
            get {
                return ResourceManager.GetString("ニ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyi.
        /// </summary>
        internal static string ニィ {
            get {
                return ResourceManager.GetString("ニィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nye.
        /// </summary>
        internal static string ニェ {
            get {
                return ResourceManager.GetString("ニェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nya.
        /// </summary>
        internal static string ニャ {
            get {
                return ResourceManager.GetString("ニャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyu.
        /// </summary>
        internal static string ニュ {
            get {
                return ResourceManager.GetString("ニュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyo.
        /// </summary>
        internal static string ニョ {
            get {
                return ResourceManager.GetString("ニョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu.
        /// </summary>
        internal static string ヌ {
            get {
                return ResourceManager.GetString("ヌ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne.
        /// </summary>
        internal static string ネ {
            get {
                return ResourceManager.GetString("ネ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string ノ {
            get {
                return ResourceManager.GetString("ノ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        internal static string ハ {
            get {
                return ResourceManager.GetString("ハ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba.
        /// </summary>
        internal static string バ {
            get {
                return ResourceManager.GetString("バ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pa.
        /// </summary>
        internal static string パ {
            get {
                return ResourceManager.GetString("パ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string ヒ {
            get {
                return ResourceManager.GetString("ヒ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bi.
        /// </summary>
        internal static string ビ {
            get {
                return ResourceManager.GetString("ビ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pi.
        /// </summary>
        internal static string ピ {
            get {
                return ResourceManager.GetString("ピ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyi.
        /// </summary>
        internal static string ヒィ {
            get {
                return ResourceManager.GetString("ヒィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byi.
        /// </summary>
        internal static string ビィ {
            get {
                return ResourceManager.GetString("ビィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pyi.
        /// </summary>
        internal static string ピィ {
            get {
                return ResourceManager.GetString("ピィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hye.
        /// </summary>
        internal static string ヒェ {
            get {
                return ResourceManager.GetString("ヒェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bye.
        /// </summary>
        internal static string ビェ {
            get {
                return ResourceManager.GetString("ビェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pye.
        /// </summary>
        internal static string ピェ {
            get {
                return ResourceManager.GetString("ピェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hya.
        /// </summary>
        internal static string ヒャ {
            get {
                return ResourceManager.GetString("ヒャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bya.
        /// </summary>
        internal static string ビャ {
            get {
                return ResourceManager.GetString("ビャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pya.
        /// </summary>
        internal static string ピャ {
            get {
                return ResourceManager.GetString("ピャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyu.
        /// </summary>
        internal static string ヒュ {
            get {
                return ResourceManager.GetString("ヒュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byu.
        /// </summary>
        internal static string ビュ {
            get {
                return ResourceManager.GetString("ビュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pyu.
        /// </summary>
        internal static string ピュ {
            get {
                return ResourceManager.GetString("ピュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyo.
        /// </summary>
        internal static string ヒョ {
            get {
                return ResourceManager.GetString("ヒョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byo.
        /// </summary>
        internal static string ビョ {
            get {
                return ResourceManager.GetString("ビョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pyo.
        /// </summary>
        internal static string ピョ {
            get {
                return ResourceManager.GetString("ピョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fu.
        /// </summary>
        internal static string フ {
            get {
                return ResourceManager.GetString("フ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bu.
        /// </summary>
        internal static string ブ {
            get {
                return ResourceManager.GetString("ブ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pu.
        /// </summary>
        internal static string プ {
            get {
                return ResourceManager.GetString("プ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        internal static string ファ {
            get {
                return ResourceManager.GetString("ファ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fi.
        /// </summary>
        internal static string フィ {
            get {
                return ResourceManager.GetString("フィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fe.
        /// </summary>
        internal static string フェ {
            get {
                return ResourceManager.GetString("フェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fo.
        /// </summary>
        internal static string フォ {
            get {
                return ResourceManager.GetString("フォ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        internal static string ヘ {
            get {
                return ResourceManager.GetString("ヘ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be.
        /// </summary>
        internal static string ベ {
            get {
                return ResourceManager.GetString("ベ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pe.
        /// </summary>
        internal static string ペ {
            get {
                return ResourceManager.GetString("ペ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ho.
        /// </summary>
        internal static string ホ {
            get {
                return ResourceManager.GetString("ホ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bo.
        /// </summary>
        internal static string ボ {
            get {
                return ResourceManager.GetString("ボ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to po.
        /// </summary>
        internal static string ポ {
            get {
                return ResourceManager.GetString("ポ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ma.
        /// </summary>
        internal static string マ {
            get {
                return ResourceManager.GetString("マ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string ミ {
            get {
                return ResourceManager.GetString("ミ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myi.
        /// </summary>
        internal static string ミィ {
            get {
                return ResourceManager.GetString("ミィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mye.
        /// </summary>
        internal static string ミェ {
            get {
                return ResourceManager.GetString("ミェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mya.
        /// </summary>
        internal static string ミャ {
            get {
                return ResourceManager.GetString("ミャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myu.
        /// </summary>
        internal static string ミュ {
            get {
                return ResourceManager.GetString("ミュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myo.
        /// </summary>
        internal static string ミョ {
            get {
                return ResourceManager.GetString("ミョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mu.
        /// </summary>
        internal static string ム {
            get {
                return ResourceManager.GetString("ム", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        internal static string メ {
            get {
                return ResourceManager.GetString("メ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mo.
        /// </summary>
        internal static string モ {
            get {
                return ResourceManager.GetString("モ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya.
        /// </summary>
        internal static string ヤ {
            get {
                return ResourceManager.GetString("ヤ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yu.
        /// </summary>
        internal static string ユ {
            get {
                return ResourceManager.GetString("ユ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo.
        /// </summary>
        internal static string ヨ {
            get {
                return ResourceManager.GetString("ヨ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ra.
        /// </summary>
        internal static string ラ {
            get {
                return ResourceManager.GetString("ラ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ri.
        /// </summary>
        internal static string リ {
            get {
                return ResourceManager.GetString("リ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ryi.
        /// </summary>
        internal static string リィ {
            get {
                return ResourceManager.GetString("リィ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rye.
        /// </summary>
        internal static string リェ {
            get {
                return ResourceManager.GetString("リェ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rya.
        /// </summary>
        internal static string リャ {
            get {
                return ResourceManager.GetString("リャ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ryu.
        /// </summary>
        internal static string リュ {
            get {
                return ResourceManager.GetString("リュ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ryo.
        /// </summary>
        internal static string リョ {
            get {
                return ResourceManager.GetString("リョ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        internal static string ル {
            get {
                return ResourceManager.GetString("ル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re.
        /// </summary>
        internal static string レ {
            get {
                return ResourceManager.GetString("レ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro.
        /// </summary>
        internal static string ロ {
            get {
                return ResourceManager.GetString("ロ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wa.
        /// </summary>
        internal static string ワ {
            get {
                return ResourceManager.GetString("ワ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wo.
        /// </summary>
        internal static string ヲ {
            get {
                return ResourceManager.GetString("ヲ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string ン {
            get {
                return ResourceManager.GetString("ン", resourceCulture);
            }
        }
    }
}
