//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Features.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RomajiToKatakana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RomajiToKatakana() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Features.Tools.LinguistResources.RomajiToKatakana", typeof(RomajiToKatakana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ド.
        /// </summary>
        internal static string _do {
            get {
                return ResourceManager.GetString("_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ア.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à バ.
        /// </summary>
        internal static string ba {
            get {
                return ResourceManager.GetString("ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ベ.
        /// </summary>
        internal static string be {
            get {
                return ResourceManager.GetString("be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ビ.
        /// </summary>
        internal static string bi {
            get {
                return ResourceManager.GetString("bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ボ.
        /// </summary>
        internal static string bo {
            get {
                return ResourceManager.GetString("bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ブ.
        /// </summary>
        internal static string bu {
            get {
                return ResourceManager.GetString("bu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ビャ.
        /// </summary>
        internal static string bya {
            get {
                return ResourceManager.GetString("bya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ビェ.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ビィ.
        /// </summary>
        internal static string byi {
            get {
                return ResourceManager.GetString("byi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ビョ.
        /// </summary>
        internal static string byo {
            get {
                return ResourceManager.GetString("byo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ビュ.
        /// </summary>
        internal static string byu {
            get {
                return ResourceManager.GetString("byu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チャ.
        /// </summary>
        internal static string cha {
            get {
                return ResourceManager.GetString("cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チェ.
        /// </summary>
        internal static string che {
            get {
                return ResourceManager.GetString("che", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チ.
        /// </summary>
        internal static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チョ.
        /// </summary>
        internal static string cho {
            get {
                return ResourceManager.GetString("cho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チュ.
        /// </summary>
        internal static string chu {
            get {
                return ResourceManager.GetString("chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ダ.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à デ.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジャ.
        /// </summary>
        internal static string dja {
            get {
                return ResourceManager.GetString("dja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジェ.
        /// </summary>
        internal static string dje {
            get {
                return ResourceManager.GetString("dje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジ.
        /// </summary>
        internal static string dji {
            get {
                return ResourceManager.GetString("dji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジョ.
        /// </summary>
        internal static string djo {
            get {
                return ResourceManager.GetString("djo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジュ.
        /// </summary>
        internal static string dju {
            get {
                return ResourceManager.GetString("dju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヂャ.
        /// </summary>
        internal static string dya {
            get {
                return ResourceManager.GetString("dya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヂェ.
        /// </summary>
        internal static string dye {
            get {
                return ResourceManager.GetString("dye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヂィ.
        /// </summary>
        internal static string dyi {
            get {
                return ResourceManager.GetString("dyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヂョ.
        /// </summary>
        internal static string dyo {
            get {
                return ResourceManager.GetString("dyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヂュ.
        /// </summary>
        internal static string dyu {
            get {
                return ResourceManager.GetString("dyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ズ.
        /// </summary>
        internal static string dzu {
            get {
                return ResourceManager.GetString("dzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à エ.
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ファ.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à フェ.
        /// </summary>
        internal static string fe {
            get {
                return ResourceManager.GetString("fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à フィ.
        /// </summary>
        internal static string fi {
            get {
                return ResourceManager.GetString("fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à フォ.
        /// </summary>
        internal static string fo {
            get {
                return ResourceManager.GetString("fo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à フ.
        /// </summary>
        internal static string fu {
            get {
                return ResourceManager.GetString("fu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ガ.
        /// </summary>
        internal static string ga {
            get {
                return ResourceManager.GetString("ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゲ.
        /// </summary>
        internal static string ge {
            get {
                return ResourceManager.GetString("ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ギ.
        /// </summary>
        internal static string gi {
            get {
                return ResourceManager.GetString("gi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゴ.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à グ.
        /// </summary>
        internal static string gu {
            get {
                return ResourceManager.GetString("gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ギャ.
        /// </summary>
        internal static string gya {
            get {
                return ResourceManager.GetString("gya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ギェ.
        /// </summary>
        internal static string gye {
            get {
                return ResourceManager.GetString("gye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ギィ.
        /// </summary>
        internal static string gyi {
            get {
                return ResourceManager.GetString("gyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ギョ.
        /// </summary>
        internal static string gyo {
            get {
                return ResourceManager.GetString("gyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ギュ.
        /// </summary>
        internal static string gyu {
            get {
                return ResourceManager.GetString("gyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ハ.
        /// </summary>
        internal static string ha {
            get {
                return ResourceManager.GetString("ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヘ.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヒ.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ホ.
        /// </summary>
        internal static string ho {
            get {
                return ResourceManager.GetString("ho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヒャ.
        /// </summary>
        internal static string hya {
            get {
                return ResourceManager.GetString("hya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヒェ.
        /// </summary>
        internal static string hye {
            get {
                return ResourceManager.GetString("hye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヒィ.
        /// </summary>
        internal static string hyi {
            get {
                return ResourceManager.GetString("hyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヒョ.
        /// </summary>
        internal static string hyo {
            get {
                return ResourceManager.GetString("hyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヒュ.
        /// </summary>
        internal static string hyu {
            get {
                return ResourceManager.GetString("hyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à イ.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジャ.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジェ.
        /// </summary>
        internal static string je {
            get {
                return ResourceManager.GetString("je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジ.
        /// </summary>
        internal static string ji {
            get {
                return ResourceManager.GetString("ji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジョ.
        /// </summary>
        internal static string jo {
            get {
                return ResourceManager.GetString("jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジュ.
        /// </summary>
        internal static string ju {
            get {
                return ResourceManager.GetString("ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジャ.
        /// </summary>
        internal static string jya {
            get {
                return ResourceManager.GetString("jya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジェ.
        /// </summary>
        internal static string jye {
            get {
                return ResourceManager.GetString("jye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジィ.
        /// </summary>
        internal static string jyi {
            get {
                return ResourceManager.GetString("jyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジョ.
        /// </summary>
        internal static string jyo {
            get {
                return ResourceManager.GetString("jyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジュ.
        /// </summary>
        internal static string jyu {
            get {
                return ResourceManager.GetString("jyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à カ.
        /// </summary>
        internal static string ka {
            get {
                return ResourceManager.GetString("ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ケ.
        /// </summary>
        internal static string ke {
            get {
                return ResourceManager.GetString("ke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à キ.
        /// </summary>
        internal static string ki {
            get {
                return ResourceManager.GetString("ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à コ.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ク.
        /// </summary>
        internal static string ku {
            get {
                return ResourceManager.GetString("ku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à キャ.
        /// </summary>
        internal static string kya {
            get {
                return ResourceManager.GetString("kya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à キェ.
        /// </summary>
        internal static string kye {
            get {
                return ResourceManager.GetString("kye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à キィ.
        /// </summary>
        internal static string kyi {
            get {
                return ResourceManager.GetString("kyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ジョ.
        /// </summary>
        internal static string kyo {
            get {
                return ResourceManager.GetString("kyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à キュ.
        /// </summary>
        internal static string kyu {
            get {
                return ResourceManager.GetString("kyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à マ.
        /// </summary>
        internal static string ma {
            get {
                return ResourceManager.GetString("ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à メ.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ミ.
        /// </summary>
        internal static string mi {
            get {
                return ResourceManager.GetString("mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à モ.
        /// </summary>
        internal static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ム.
        /// </summary>
        internal static string mu {
            get {
                return ResourceManager.GetString("mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ミャ.
        /// </summary>
        internal static string mya {
            get {
                return ResourceManager.GetString("mya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ミェ.
        /// </summary>
        internal static string mye {
            get {
                return ResourceManager.GetString("mye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ミィ.
        /// </summary>
        internal static string myi {
            get {
                return ResourceManager.GetString("myi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ミョ.
        /// </summary>
        internal static string myo {
            get {
                return ResourceManager.GetString("myo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ミュ.
        /// </summary>
        internal static string myu {
            get {
                return ResourceManager.GetString("myu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ン.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ナ.
        /// </summary>
        internal static string na {
            get {
                return ResourceManager.GetString("na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ネ.
        /// </summary>
        internal static string ne {
            get {
                return ResourceManager.GetString("ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ニ.
        /// </summary>
        internal static string ni {
            get {
                return ResourceManager.GetString("ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ノ.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヌ.
        /// </summary>
        internal static string nu {
            get {
                return ResourceManager.GetString("nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ニャ.
        /// </summary>
        internal static string nya {
            get {
                return ResourceManager.GetString("nya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ニェ.
        /// </summary>
        internal static string nye {
            get {
                return ResourceManager.GetString("nye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ニィ.
        /// </summary>
        internal static string nyi {
            get {
                return ResourceManager.GetString("nyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ニョ.
        /// </summary>
        internal static string nyo {
            get {
                return ResourceManager.GetString("nyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ニュ.
        /// </summary>
        internal static string nyu {
            get {
                return ResourceManager.GetString("nyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à オ.
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à パ.
        /// </summary>
        internal static string pa {
            get {
                return ResourceManager.GetString("pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ペ.
        /// </summary>
        internal static string pe {
            get {
                return ResourceManager.GetString("pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ピ.
        /// </summary>
        internal static string pi {
            get {
                return ResourceManager.GetString("pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ポ.
        /// </summary>
        internal static string po {
            get {
                return ResourceManager.GetString("po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à プ.
        /// </summary>
        internal static string pu {
            get {
                return ResourceManager.GetString("pu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ピャ.
        /// </summary>
        internal static string pya {
            get {
                return ResourceManager.GetString("pya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ピェ.
        /// </summary>
        internal static string pye {
            get {
                return ResourceManager.GetString("pye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ピィ.
        /// </summary>
        internal static string pyi {
            get {
                return ResourceManager.GetString("pyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ピョ.
        /// </summary>
        internal static string pyo {
            get {
                return ResourceManager.GetString("pyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ピュ.
        /// </summary>
        internal static string pyu {
            get {
                return ResourceManager.GetString("pyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ラ.
        /// </summary>
        internal static string ra {
            get {
                return ResourceManager.GetString("ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à レ.
        /// </summary>
        internal static string re {
            get {
                return ResourceManager.GetString("re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リ.
        /// </summary>
        internal static string ri {
            get {
                return ResourceManager.GetString("ri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ロ.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ル.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リャ.
        /// </summary>
        internal static string rya {
            get {
                return ResourceManager.GetString("rya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リェ.
        /// </summary>
        internal static string rye {
            get {
                return ResourceManager.GetString("rye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リィ.
        /// </summary>
        internal static string ryi {
            get {
                return ResourceManager.GetString("ryi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リョ.
        /// </summary>
        internal static string ryo {
            get {
                return ResourceManager.GetString("ryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リュ.
        /// </summary>
        internal static string ryu {
            get {
                return ResourceManager.GetString("ryu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à サ.
        /// </summary>
        internal static string sa {
            get {
                return ResourceManager.GetString("sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à セ.
        /// </summary>
        internal static string se {
            get {
                return ResourceManager.GetString("se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à シャ.
        /// </summary>
        internal static string sha {
            get {
                return ResourceManager.GetString("sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à シェ.
        /// </summary>
        internal static string she {
            get {
                return ResourceManager.GetString("she", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à シ.
        /// </summary>
        internal static string shi {
            get {
                return ResourceManager.GetString("shi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ショ.
        /// </summary>
        internal static string sho {
            get {
                return ResourceManager.GetString("sho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à シュ.
        /// </summary>
        internal static string shu {
            get {
                return ResourceManager.GetString("shu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ソ.
        /// </summary>
        internal static string so {
            get {
                return ResourceManager.GetString("so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ス.
        /// </summary>
        internal static string su {
            get {
                return ResourceManager.GetString("su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à タ.
        /// </summary>
        internal static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à テ.
        /// </summary>
        internal static string te {
            get {
                return ResourceManager.GetString("te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ト.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ツ.
        /// </summary>
        internal static string tsu {
            get {
                return ResourceManager.GetString("tsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チャ.
        /// </summary>
        internal static string tya {
            get {
                return ResourceManager.GetString("tya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チェ.
        /// </summary>
        internal static string tye {
            get {
                return ResourceManager.GetString("tye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チィ.
        /// </summary>
        internal static string tyi {
            get {
                return ResourceManager.GetString("tyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チョ.
        /// </summary>
        internal static string tyo {
            get {
                return ResourceManager.GetString("tyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à チュ.
        /// </summary>
        internal static string tyu {
            get {
                return ResourceManager.GetString("tyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ウ.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヴァ.
        /// </summary>
        internal static string va {
            get {
                return ResourceManager.GetString("va", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヴェ.
        /// </summary>
        internal static string ve {
            get {
                return ResourceManager.GetString("ve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヴィ.
        /// </summary>
        internal static string vi {
            get {
                return ResourceManager.GetString("vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヴォ.
        /// </summary>
        internal static string vo {
            get {
                return ResourceManager.GetString("vo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヴ.
        /// </summary>
        internal static string vu {
            get {
                return ResourceManager.GetString("vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ワ.
        /// </summary>
        internal static string wa {
            get {
                return ResourceManager.GetString("wa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ウェ.
        /// </summary>
        internal static string we {
            get {
                return ResourceManager.GetString("we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ウィ.
        /// </summary>
        internal static string wi {
            get {
                return ResourceManager.GetString("wi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヲ.
        /// </summary>
        internal static string wo {
            get {
                return ResourceManager.GetString("wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヤ.
        /// </summary>
        internal static string ya {
            get {
                return ResourceManager.GetString("ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ヨ.
        /// </summary>
        internal static string yo {
            get {
                return ResourceManager.GetString("yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ユ.
        /// </summary>
        internal static string yu {
            get {
                return ResourceManager.GetString("yu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ザ.
        /// </summary>
        internal static string za {
            get {
                return ResourceManager.GetString("za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゼ.
        /// </summary>
        internal static string ze {
            get {
                return ResourceManager.GetString("ze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゾ.
        /// </summary>
        internal static string zo {
            get {
                return ResourceManager.GetString("zo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ズ.
        /// </summary>
        internal static string zu {
            get {
                return ResourceManager.GetString("zu", resourceCulture);
            }
        }
    }
}
