//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Features.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RomajiToHiragana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RomajiToHiragana() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Features.Tools.LinguistResources.RomajiToHiragana", typeof(RomajiToHiragana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ど.
        /// </summary>
        internal static string _do {
            get {
                return ResourceManager.GetString("_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à あ.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ば.
        /// </summary>
        internal static string ba {
            get {
                return ResourceManager.GetString("ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à べ.
        /// </summary>
        internal static string be {
            get {
                return ResourceManager.GetString("be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à び.
        /// </summary>
        internal static string bi {
            get {
                return ResourceManager.GetString("bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぼ.
        /// </summary>
        internal static string bo {
            get {
                return ResourceManager.GetString("bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぶ.
        /// </summary>
        internal static string bu {
            get {
                return ResourceManager.GetString("bu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à びゃ.
        /// </summary>
        internal static string bya {
            get {
                return ResourceManager.GetString("bya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à びぇ.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à びぃ.
        /// </summary>
        internal static string byi {
            get {
                return ResourceManager.GetString("byi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à びょ.
        /// </summary>
        internal static string byo {
            get {
                return ResourceManager.GetString("byo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à びゅ.
        /// </summary>
        internal static string byu {
            get {
                return ResourceManager.GetString("byu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちゃ.
        /// </summary>
        internal static string cha {
            get {
                return ResourceManager.GetString("cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちぇ.
        /// </summary>
        internal static string che {
            get {
                return ResourceManager.GetString("che", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ち.
        /// </summary>
        internal static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちょ.
        /// </summary>
        internal static string cho {
            get {
                return ResourceManager.GetString("cho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちゅ.
        /// </summary>
        internal static string chu {
            get {
                return ResourceManager.GetString("chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à だ.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à で.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じゃ.
        /// </summary>
        internal static string dja {
            get {
                return ResourceManager.GetString("dja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じぇ.
        /// </summary>
        internal static string dje {
            get {
                return ResourceManager.GetString("dje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じ.
        /// </summary>
        internal static string dji {
            get {
                return ResourceManager.GetString("dji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じょ.
        /// </summary>
        internal static string djo {
            get {
                return ResourceManager.GetString("djo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じゅ.
        /// </summary>
        internal static string dju {
            get {
                return ResourceManager.GetString("dju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぢゃ.
        /// </summary>
        internal static string dya {
            get {
                return ResourceManager.GetString("dya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぢぇ.
        /// </summary>
        internal static string dye {
            get {
                return ResourceManager.GetString("dye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぢぃ.
        /// </summary>
        internal static string dyi {
            get {
                return ResourceManager.GetString("dyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぢょ.
        /// </summary>
        internal static string dyo {
            get {
                return ResourceManager.GetString("dyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぢゅ.
        /// </summary>
        internal static string dyu {
            get {
                return ResourceManager.GetString("dyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à づ.
        /// </summary>
        internal static string dzu {
            get {
                return ResourceManager.GetString("dzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à え.
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ふぁ.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ふぇ.
        /// </summary>
        internal static string fe {
            get {
                return ResourceManager.GetString("fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ふぃ.
        /// </summary>
        internal static string fi {
            get {
                return ResourceManager.GetString("fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ふぉ.
        /// </summary>
        internal static string fo {
            get {
                return ResourceManager.GetString("fo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ふ.
        /// </summary>
        internal static string fu {
            get {
                return ResourceManager.GetString("fu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à が.
        /// </summary>
        internal static string ga {
            get {
                return ResourceManager.GetString("ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à げ.
        /// </summary>
        internal static string ge {
            get {
                return ResourceManager.GetString("ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぎ.
        /// </summary>
        internal static string gi {
            get {
                return ResourceManager.GetString("gi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ご.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぐ.
        /// </summary>
        internal static string gu {
            get {
                return ResourceManager.GetString("gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぎゃ.
        /// </summary>
        internal static string gya {
            get {
                return ResourceManager.GetString("gya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぎぇ.
        /// </summary>
        internal static string gye {
            get {
                return ResourceManager.GetString("gye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぎぃ.
        /// </summary>
        internal static string gyi {
            get {
                return ResourceManager.GetString("gyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぎょ.
        /// </summary>
        internal static string gyo {
            get {
                return ResourceManager.GetString("gyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぎゅ.
        /// </summary>
        internal static string gyu {
            get {
                return ResourceManager.GetString("gyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à は.
        /// </summary>
        internal static string ha {
            get {
                return ResourceManager.GetString("ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à へ.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ひ.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ほ.
        /// </summary>
        internal static string ho {
            get {
                return ResourceManager.GetString("ho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ひゃ.
        /// </summary>
        internal static string hya {
            get {
                return ResourceManager.GetString("hya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ひぇ.
        /// </summary>
        internal static string hye {
            get {
                return ResourceManager.GetString("hye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ひぃ.
        /// </summary>
        internal static string hyi {
            get {
                return ResourceManager.GetString("hyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ひょ.
        /// </summary>
        internal static string hyo {
            get {
                return ResourceManager.GetString("hyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ひゅ.
        /// </summary>
        internal static string hyu {
            get {
                return ResourceManager.GetString("hyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à い.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じゃ.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じぇ.
        /// </summary>
        internal static string je {
            get {
                return ResourceManager.GetString("je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じ.
        /// </summary>
        internal static string ji {
            get {
                return ResourceManager.GetString("ji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じょ.
        /// </summary>
        internal static string jo {
            get {
                return ResourceManager.GetString("jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じゅ.
        /// </summary>
        internal static string ju {
            get {
                return ResourceManager.GetString("ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じゃ.
        /// </summary>
        internal static string jya {
            get {
                return ResourceManager.GetString("jya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じぇ.
        /// </summary>
        internal static string jye {
            get {
                return ResourceManager.GetString("jye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じぃ.
        /// </summary>
        internal static string jyi {
            get {
                return ResourceManager.GetString("jyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じょ.
        /// </summary>
        internal static string jyo {
            get {
                return ResourceManager.GetString("jyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à じゅ.
        /// </summary>
        internal static string jyu {
            get {
                return ResourceManager.GetString("jyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à か.
        /// </summary>
        internal static string ka {
            get {
                return ResourceManager.GetString("ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à け.
        /// </summary>
        internal static string ke {
            get {
                return ResourceManager.GetString("ke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à き.
        /// </summary>
        internal static string ki {
            get {
                return ResourceManager.GetString("ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à こ.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à く.
        /// </summary>
        internal static string ku {
            get {
                return ResourceManager.GetString("ku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à きゃ.
        /// </summary>
        internal static string kya {
            get {
                return ResourceManager.GetString("kya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à きぇ.
        /// </summary>
        internal static string kye {
            get {
                return ResourceManager.GetString("kye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à きぃ.
        /// </summary>
        internal static string kyi {
            get {
                return ResourceManager.GetString("kyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à きょ.
        /// </summary>
        internal static string kyo {
            get {
                return ResourceManager.GetString("kyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à きゅ.
        /// </summary>
        internal static string kyu {
            get {
                return ResourceManager.GetString("kyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ま.
        /// </summary>
        internal static string ma {
            get {
                return ResourceManager.GetString("ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à め.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à み.
        /// </summary>
        internal static string mi {
            get {
                return ResourceManager.GetString("mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à も.
        /// </summary>
        internal static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à む.
        /// </summary>
        internal static string mu {
            get {
                return ResourceManager.GetString("mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à みゃ.
        /// </summary>
        internal static string mya {
            get {
                return ResourceManager.GetString("mya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à みぇ.
        /// </summary>
        internal static string mye {
            get {
                return ResourceManager.GetString("mye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à みぃ.
        /// </summary>
        internal static string myi {
            get {
                return ResourceManager.GetString("myi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à みょ.
        /// </summary>
        internal static string myo {
            get {
                return ResourceManager.GetString("myo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à みゅ.
        /// </summary>
        internal static string myu {
            get {
                return ResourceManager.GetString("myu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ん.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à な.
        /// </summary>
        internal static string na {
            get {
                return ResourceManager.GetString("na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ね.
        /// </summary>
        internal static string ne {
            get {
                return ResourceManager.GetString("ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à に.
        /// </summary>
        internal static string ni {
            get {
                return ResourceManager.GetString("ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à の.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぬ.
        /// </summary>
        internal static string nu {
            get {
                return ResourceManager.GetString("nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à にゃ.
        /// </summary>
        internal static string nya {
            get {
                return ResourceManager.GetString("nya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à にぇ.
        /// </summary>
        internal static string nye {
            get {
                return ResourceManager.GetString("nye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à にぃ.
        /// </summary>
        internal static string nyi {
            get {
                return ResourceManager.GetString("nyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à にょ.
        /// </summary>
        internal static string nyo {
            get {
                return ResourceManager.GetString("nyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à にゅ.
        /// </summary>
        internal static string nyu {
            get {
                return ResourceManager.GetString("nyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à お.
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぱ.
        /// </summary>
        internal static string pa {
            get {
                return ResourceManager.GetString("pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぺ.
        /// </summary>
        internal static string pe {
            get {
                return ResourceManager.GetString("pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぴ.
        /// </summary>
        internal static string pi {
            get {
                return ResourceManager.GetString("pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぽ.
        /// </summary>
        internal static string po {
            get {
                return ResourceManager.GetString("po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぷ.
        /// </summary>
        internal static string pu {
            get {
                return ResourceManager.GetString("pu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぴゃ.
        /// </summary>
        internal static string pya {
            get {
                return ResourceManager.GetString("pya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぴぇ.
        /// </summary>
        internal static string pye {
            get {
                return ResourceManager.GetString("pye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぴぃ.
        /// </summary>
        internal static string pyi {
            get {
                return ResourceManager.GetString("pyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぴょ.
        /// </summary>
        internal static string pyo {
            get {
                return ResourceManager.GetString("pyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぴゅ.
        /// </summary>
        internal static string pyu {
            get {
                return ResourceManager.GetString("pyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ら.
        /// </summary>
        internal static string ra {
            get {
                return ResourceManager.GetString("ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à れ.
        /// </summary>
        internal static string re {
            get {
                return ResourceManager.GetString("re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à り.
        /// </summary>
        internal static string ri {
            get {
                return ResourceManager.GetString("ri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ろ.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à る.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à りゃ.
        /// </summary>
        internal static string rya {
            get {
                return ResourceManager.GetString("rya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à りぇ.
        /// </summary>
        internal static string rye {
            get {
                return ResourceManager.GetString("rye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à りぃ.
        /// </summary>
        internal static string ryi {
            get {
                return ResourceManager.GetString("ryi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à りょ.
        /// </summary>
        internal static string ryo {
            get {
                return ResourceManager.GetString("ryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à りゅ.
        /// </summary>
        internal static string ryu {
            get {
                return ResourceManager.GetString("ryu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à さ.
        /// </summary>
        internal static string sa {
            get {
                return ResourceManager.GetString("sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à せ.
        /// </summary>
        internal static string se {
            get {
                return ResourceManager.GetString("se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à しゃ.
        /// </summary>
        internal static string sha {
            get {
                return ResourceManager.GetString("sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à しぇ.
        /// </summary>
        internal static string she {
            get {
                return ResourceManager.GetString("she", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à し.
        /// </summary>
        internal static string shi {
            get {
                return ResourceManager.GetString("shi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à しょ.
        /// </summary>
        internal static string sho {
            get {
                return ResourceManager.GetString("sho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à しゅ.
        /// </summary>
        internal static string shu {
            get {
                return ResourceManager.GetString("shu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à そ.
        /// </summary>
        internal static string so {
            get {
                return ResourceManager.GetString("so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à す.
        /// </summary>
        internal static string su {
            get {
                return ResourceManager.GetString("su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à た.
        /// </summary>
        internal static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à て.
        /// </summary>
        internal static string te {
            get {
                return ResourceManager.GetString("te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à と.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à つ.
        /// </summary>
        internal static string tsu {
            get {
                return ResourceManager.GetString("tsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちゃ.
        /// </summary>
        internal static string tya {
            get {
                return ResourceManager.GetString("tya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちぇ.
        /// </summary>
        internal static string tye {
            get {
                return ResourceManager.GetString("tye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちぃ.
        /// </summary>
        internal static string tyi {
            get {
                return ResourceManager.GetString("tyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちょ.
        /// </summary>
        internal static string tyo {
            get {
                return ResourceManager.GetString("tyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ちゅ.
        /// </summary>
        internal static string tyu {
            get {
                return ResourceManager.GetString("tyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à う.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゔ.
        /// </summary>
        internal static string vu {
            get {
                return ResourceManager.GetString("vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à わ.
        /// </summary>
        internal static string wa {
            get {
                return ResourceManager.GetString("wa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゑ.
        /// </summary>
        internal static string we {
            get {
                return ResourceManager.GetString("we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゐ.
        /// </summary>
        internal static string wi {
            get {
                return ResourceManager.GetString("wi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à を.
        /// </summary>
        internal static string wo {
            get {
                return ResourceManager.GetString("wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à や.
        /// </summary>
        internal static string ya {
            get {
                return ResourceManager.GetString("ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à よ.
        /// </summary>
        internal static string yo {
            get {
                return ResourceManager.GetString("yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ゆ.
        /// </summary>
        internal static string yu {
            get {
                return ResourceManager.GetString("yu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ざ.
        /// </summary>
        internal static string za {
            get {
                return ResourceManager.GetString("za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぜ.
        /// </summary>
        internal static string ze {
            get {
                return ResourceManager.GetString("ze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ぞ.
        /// </summary>
        internal static string zo {
            get {
                return ResourceManager.GetString("zo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ず.
        /// </summary>
        internal static string zu {
            get {
                return ResourceManager.GetString("zu", resourceCulture);
            }
        }
    }
}
