//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Modules.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RomajiToHiragana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RomajiToHiragana() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Modules.Tools.LinguistResources.RomajiToHiragana", typeof(RomajiToHiragana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ど.
        /// </summary>
        internal static string _do {
            get {
                return ResourceManager.GetString("_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あ.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ば.
        /// </summary>
        internal static string ba {
            get {
                return ResourceManager.GetString("ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to べ.
        /// </summary>
        internal static string be {
            get {
                return ResourceManager.GetString("be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to び.
        /// </summary>
        internal static string bi {
            get {
                return ResourceManager.GetString("bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぼ.
        /// </summary>
        internal static string bo {
            get {
                return ResourceManager.GetString("bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぶ.
        /// </summary>
        internal static string bu {
            get {
                return ResourceManager.GetString("bu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to びゃ.
        /// </summary>
        internal static string bya {
            get {
                return ResourceManager.GetString("bya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to びぇ.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to びぃ.
        /// </summary>
        internal static string byi {
            get {
                return ResourceManager.GetString("byi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to びょ.
        /// </summary>
        internal static string byo {
            get {
                return ResourceManager.GetString("byo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to びゅ.
        /// </summary>
        internal static string byu {
            get {
                return ResourceManager.GetString("byu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちゃ.
        /// </summary>
        internal static string cha {
            get {
                return ResourceManager.GetString("cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちぇ.
        /// </summary>
        internal static string che {
            get {
                return ResourceManager.GetString("che", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ち.
        /// </summary>
        internal static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちょ.
        /// </summary>
        internal static string cho {
            get {
                return ResourceManager.GetString("cho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちゅ.
        /// </summary>
        internal static string chu {
            get {
                return ResourceManager.GetString("chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to だ.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to で.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じゃ.
        /// </summary>
        internal static string dja {
            get {
                return ResourceManager.GetString("dja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じぇ.
        /// </summary>
        internal static string dje {
            get {
                return ResourceManager.GetString("dje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じ.
        /// </summary>
        internal static string dji {
            get {
                return ResourceManager.GetString("dji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じょ.
        /// </summary>
        internal static string djo {
            get {
                return ResourceManager.GetString("djo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じゅ.
        /// </summary>
        internal static string dju {
            get {
                return ResourceManager.GetString("dju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぢゃ.
        /// </summary>
        internal static string dya {
            get {
                return ResourceManager.GetString("dya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぢぇ.
        /// </summary>
        internal static string dye {
            get {
                return ResourceManager.GetString("dye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぢぃ.
        /// </summary>
        internal static string dyi {
            get {
                return ResourceManager.GetString("dyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぢょ.
        /// </summary>
        internal static string dyo {
            get {
                return ResourceManager.GetString("dyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぢゅ.
        /// </summary>
        internal static string dyu {
            get {
                return ResourceManager.GetString("dyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to づ.
        /// </summary>
        internal static string dzu {
            get {
                return ResourceManager.GetString("dzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to え.
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふぁ.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふぇ.
        /// </summary>
        internal static string fe {
            get {
                return ResourceManager.GetString("fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふぃ.
        /// </summary>
        internal static string fi {
            get {
                return ResourceManager.GetString("fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふぉ.
        /// </summary>
        internal static string fo {
            get {
                return ResourceManager.GetString("fo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふ.
        /// </summary>
        internal static string fu {
            get {
                return ResourceManager.GetString("fu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to が.
        /// </summary>
        internal static string ga {
            get {
                return ResourceManager.GetString("ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to げ.
        /// </summary>
        internal static string ge {
            get {
                return ResourceManager.GetString("ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぎ.
        /// </summary>
        internal static string gi {
            get {
                return ResourceManager.GetString("gi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ご.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぐ.
        /// </summary>
        internal static string gu {
            get {
                return ResourceManager.GetString("gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぎゃ.
        /// </summary>
        internal static string gya {
            get {
                return ResourceManager.GetString("gya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぎぇ.
        /// </summary>
        internal static string gye {
            get {
                return ResourceManager.GetString("gye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぎぃ.
        /// </summary>
        internal static string gyi {
            get {
                return ResourceManager.GetString("gyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぎょ.
        /// </summary>
        internal static string gyo {
            get {
                return ResourceManager.GetString("gyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぎゅ.
        /// </summary>
        internal static string gyu {
            get {
                return ResourceManager.GetString("gyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to は.
        /// </summary>
        internal static string ha {
            get {
                return ResourceManager.GetString("ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to へ.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひ.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ほ.
        /// </summary>
        internal static string ho {
            get {
                return ResourceManager.GetString("ho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひゃ.
        /// </summary>
        internal static string hya {
            get {
                return ResourceManager.GetString("hya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひぇ.
        /// </summary>
        internal static string hye {
            get {
                return ResourceManager.GetString("hye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひぃ.
        /// </summary>
        internal static string hyi {
            get {
                return ResourceManager.GetString("hyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひょ.
        /// </summary>
        internal static string hyo {
            get {
                return ResourceManager.GetString("hyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひゅ.
        /// </summary>
        internal static string hyu {
            get {
                return ResourceManager.GetString("hyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to い.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じゃ.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じぇ.
        /// </summary>
        internal static string je {
            get {
                return ResourceManager.GetString("je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じ.
        /// </summary>
        internal static string ji {
            get {
                return ResourceManager.GetString("ji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じょ.
        /// </summary>
        internal static string jo {
            get {
                return ResourceManager.GetString("jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じゅ.
        /// </summary>
        internal static string ju {
            get {
                return ResourceManager.GetString("ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じゃ.
        /// </summary>
        internal static string jya {
            get {
                return ResourceManager.GetString("jya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じぇ.
        /// </summary>
        internal static string jye {
            get {
                return ResourceManager.GetString("jye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じぃ.
        /// </summary>
        internal static string jyi {
            get {
                return ResourceManager.GetString("jyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じょ.
        /// </summary>
        internal static string jyo {
            get {
                return ResourceManager.GetString("jyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to じゅ.
        /// </summary>
        internal static string jyu {
            get {
                return ResourceManager.GetString("jyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to か.
        /// </summary>
        internal static string ka {
            get {
                return ResourceManager.GetString("ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to け.
        /// </summary>
        internal static string ke {
            get {
                return ResourceManager.GetString("ke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to き.
        /// </summary>
        internal static string ki {
            get {
                return ResourceManager.GetString("ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to こ.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to く.
        /// </summary>
        internal static string ku {
            get {
                return ResourceManager.GetString("ku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きゃ.
        /// </summary>
        internal static string kya {
            get {
                return ResourceManager.GetString("kya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きぇ.
        /// </summary>
        internal static string kye {
            get {
                return ResourceManager.GetString("kye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きぃ.
        /// </summary>
        internal static string kyi {
            get {
                return ResourceManager.GetString("kyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きょ.
        /// </summary>
        internal static string kyo {
            get {
                return ResourceManager.GetString("kyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きゅ.
        /// </summary>
        internal static string kyu {
            get {
                return ResourceManager.GetString("kyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ま.
        /// </summary>
        internal static string ma {
            get {
                return ResourceManager.GetString("ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to め.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to み.
        /// </summary>
        internal static string mi {
            get {
                return ResourceManager.GetString("mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to も.
        /// </summary>
        internal static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to む.
        /// </summary>
        internal static string mu {
            get {
                return ResourceManager.GetString("mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to みゃ.
        /// </summary>
        internal static string mya {
            get {
                return ResourceManager.GetString("mya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to みぇ.
        /// </summary>
        internal static string mye {
            get {
                return ResourceManager.GetString("mye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to みぃ.
        /// </summary>
        internal static string myi {
            get {
                return ResourceManager.GetString("myi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to みょ.
        /// </summary>
        internal static string myo {
            get {
                return ResourceManager.GetString("myo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to みゅ.
        /// </summary>
        internal static string myu {
            get {
                return ResourceManager.GetString("myu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ん.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to な.
        /// </summary>
        internal static string na {
            get {
                return ResourceManager.GetString("na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ね.
        /// </summary>
        internal static string ne {
            get {
                return ResourceManager.GetString("ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to に.
        /// </summary>
        internal static string ni {
            get {
                return ResourceManager.GetString("ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to の.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぬ.
        /// </summary>
        internal static string nu {
            get {
                return ResourceManager.GetString("nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to にゃ.
        /// </summary>
        internal static string nya {
            get {
                return ResourceManager.GetString("nya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to にぇ.
        /// </summary>
        internal static string nye {
            get {
                return ResourceManager.GetString("nye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to にぃ.
        /// </summary>
        internal static string nyi {
            get {
                return ResourceManager.GetString("nyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to にょ.
        /// </summary>
        internal static string nyo {
            get {
                return ResourceManager.GetString("nyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to にゅ.
        /// </summary>
        internal static string nyu {
            get {
                return ResourceManager.GetString("nyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お.
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぱ.
        /// </summary>
        internal static string pa {
            get {
                return ResourceManager.GetString("pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぺ.
        /// </summary>
        internal static string pe {
            get {
                return ResourceManager.GetString("pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴ.
        /// </summary>
        internal static string pi {
            get {
                return ResourceManager.GetString("pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぽ.
        /// </summary>
        internal static string po {
            get {
                return ResourceManager.GetString("po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぷ.
        /// </summary>
        internal static string pu {
            get {
                return ResourceManager.GetString("pu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴゃ.
        /// </summary>
        internal static string pya {
            get {
                return ResourceManager.GetString("pya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴぇ.
        /// </summary>
        internal static string pye {
            get {
                return ResourceManager.GetString("pye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴぃ.
        /// </summary>
        internal static string pyi {
            get {
                return ResourceManager.GetString("pyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴょ.
        /// </summary>
        internal static string pyo {
            get {
                return ResourceManager.GetString("pyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴゅ.
        /// </summary>
        internal static string pyu {
            get {
                return ResourceManager.GetString("pyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ら.
        /// </summary>
        internal static string ra {
            get {
                return ResourceManager.GetString("ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to れ.
        /// </summary>
        internal static string re {
            get {
                return ResourceManager.GetString("re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to り.
        /// </summary>
        internal static string ri {
            get {
                return ResourceManager.GetString("ri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ろ.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to る.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to りゃ.
        /// </summary>
        internal static string rya {
            get {
                return ResourceManager.GetString("rya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to りぇ.
        /// </summary>
        internal static string rye {
            get {
                return ResourceManager.GetString("rye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to りぃ.
        /// </summary>
        internal static string ryi {
            get {
                return ResourceManager.GetString("ryi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to りょ.
        /// </summary>
        internal static string ryo {
            get {
                return ResourceManager.GetString("ryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to りゅ.
        /// </summary>
        internal static string ryu {
            get {
                return ResourceManager.GetString("ryu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to さ.
        /// </summary>
        internal static string sa {
            get {
                return ResourceManager.GetString("sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to せ.
        /// </summary>
        internal static string se {
            get {
                return ResourceManager.GetString("se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しゃ.
        /// </summary>
        internal static string sha {
            get {
                return ResourceManager.GetString("sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しぇ.
        /// </summary>
        internal static string she {
            get {
                return ResourceManager.GetString("she", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to し.
        /// </summary>
        internal static string shi {
            get {
                return ResourceManager.GetString("shi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しょ.
        /// </summary>
        internal static string sho {
            get {
                return ResourceManager.GetString("sho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しゅ.
        /// </summary>
        internal static string shu {
            get {
                return ResourceManager.GetString("shu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to そ.
        /// </summary>
        internal static string so {
            get {
                return ResourceManager.GetString("so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to す.
        /// </summary>
        internal static string su {
            get {
                return ResourceManager.GetString("su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to た.
        /// </summary>
        internal static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to て.
        /// </summary>
        internal static string te {
            get {
                return ResourceManager.GetString("te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to と.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to つ.
        /// </summary>
        internal static string tsu {
            get {
                return ResourceManager.GetString("tsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちゃ.
        /// </summary>
        internal static string tya {
            get {
                return ResourceManager.GetString("tya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちぇ.
        /// </summary>
        internal static string tye {
            get {
                return ResourceManager.GetString("tye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちぃ.
        /// </summary>
        internal static string tyi {
            get {
                return ResourceManager.GetString("tyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちょ.
        /// </summary>
        internal static string tyo {
            get {
                return ResourceManager.GetString("tyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ちゅ.
        /// </summary>
        internal static string tyu {
            get {
                return ResourceManager.GetString("tyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to う.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゔ.
        /// </summary>
        internal static string vu {
            get {
                return ResourceManager.GetString("vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to わ.
        /// </summary>
        internal static string wa {
            get {
                return ResourceManager.GetString("wa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゑ.
        /// </summary>
        internal static string we {
            get {
                return ResourceManager.GetString("we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゐ.
        /// </summary>
        internal static string wi {
            get {
                return ResourceManager.GetString("wi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to を.
        /// </summary>
        internal static string wo {
            get {
                return ResourceManager.GetString("wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to や.
        /// </summary>
        internal static string ya {
            get {
                return ResourceManager.GetString("ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to よ.
        /// </summary>
        internal static string yo {
            get {
                return ResourceManager.GetString("yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゆ.
        /// </summary>
        internal static string yu {
            get {
                return ResourceManager.GetString("yu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ざ.
        /// </summary>
        internal static string za {
            get {
                return ResourceManager.GetString("za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぜ.
        /// </summary>
        internal static string ze {
            get {
                return ResourceManager.GetString("ze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぞ.
        /// </summary>
        internal static string zo {
            get {
                return ResourceManager.GetString("zo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ず.
        /// </summary>
        internal static string zu {
            get {
                return ResourceManager.GetString("zu", resourceCulture);
            }
        }
    }
}
