//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HiraganaToRomaji {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HiraganaToRomaji() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Tools.LinguistResources.HiraganaToRomaji", typeof(HiraganaToRomaji).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string あ {
            get {
                return ResourceManager.GetString("あ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string い {
            get {
                return ResourceManager.GetString("い", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ye.
        /// </summary>
        internal static string いぇ {
            get {
                return ResourceManager.GetString("いぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        internal static string う {
            get {
                return ResourceManager.GetString("う", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vu.
        /// </summary>
        internal static string ゔ {
            get {
                return ResourceManager.GetString("ゔ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        internal static string え {
            get {
                return ResourceManager.GetString("え", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string お {
            get {
                return ResourceManager.GetString("お", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka.
        /// </summary>
        internal static string か {
            get {
                return ResourceManager.GetString("か", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ga.
        /// </summary>
        internal static string が {
            get {
                return ResourceManager.GetString("が", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ki.
        /// </summary>
        internal static string き {
            get {
                return ResourceManager.GetString("き", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gi.
        /// </summary>
        internal static string ぎ {
            get {
                return ResourceManager.GetString("ぎ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyi.
        /// </summary>
        internal static string きぃ {
            get {
                return ResourceManager.GetString("きぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gyi.
        /// </summary>
        internal static string ぎぃ {
            get {
                return ResourceManager.GetString("ぎぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kye.
        /// </summary>
        internal static string きぇ {
            get {
                return ResourceManager.GetString("きぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gye.
        /// </summary>
        internal static string ぎぇ {
            get {
                return ResourceManager.GetString("ぎぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kya.
        /// </summary>
        internal static string きゃ {
            get {
                return ResourceManager.GetString("きゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gya.
        /// </summary>
        internal static string ぎゃ {
            get {
                return ResourceManager.GetString("ぎゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyu.
        /// </summary>
        internal static string きゅ {
            get {
                return ResourceManager.GetString("きゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gyu.
        /// </summary>
        internal static string ぎゅ {
            get {
                return ResourceManager.GetString("ぎゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyo.
        /// </summary>
        internal static string きょ {
            get {
                return ResourceManager.GetString("きょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gyo.
        /// </summary>
        internal static string ぎょ {
            get {
                return ResourceManager.GetString("ぎょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ku.
        /// </summary>
        internal static string く {
            get {
                return ResourceManager.GetString("く", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gu.
        /// </summary>
        internal static string ぐ {
            get {
                return ResourceManager.GetString("ぐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ke.
        /// </summary>
        internal static string け {
            get {
                return ResourceManager.GetString("け", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ge.
        /// </summary>
        internal static string げ {
            get {
                return ResourceManager.GetString("げ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.
        /// </summary>
        internal static string こ {
            get {
                return ResourceManager.GetString("こ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        internal static string ご {
            get {
                return ResourceManager.GetString("ご", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string さ {
            get {
                return ResourceManager.GetString("さ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za.
        /// </summary>
        internal static string ざ {
            get {
                return ResourceManager.GetString("ざ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shi.
        /// </summary>
        internal static string し {
            get {
                return ResourceManager.GetString("し", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ji.
        /// </summary>
        internal static string じ {
            get {
                return ResourceManager.GetString("じ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ji.
        /// </summary>
        internal static string じぃ {
            get {
                return ResourceManager.GetString("じぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to she.
        /// </summary>
        internal static string しぇ {
            get {
                return ResourceManager.GetString("しぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je.
        /// </summary>
        internal static string じぇ {
            get {
                return ResourceManager.GetString("じぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha.
        /// </summary>
        internal static string しゃ {
            get {
                return ResourceManager.GetString("しゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string じゃ {
            get {
                return ResourceManager.GetString("じゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shu.
        /// </summary>
        internal static string しゅ {
            get {
                return ResourceManager.GetString("しゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ju.
        /// </summary>
        internal static string じゅ {
            get {
                return ResourceManager.GetString("じゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sho.
        /// </summary>
        internal static string しょ {
            get {
                return ResourceManager.GetString("しょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jo.
        /// </summary>
        internal static string じょ {
            get {
                return ResourceManager.GetString("じょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to su.
        /// </summary>
        internal static string す {
            get {
                return ResourceManager.GetString("す", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zu.
        /// </summary>
        internal static string ず {
            get {
                return ResourceManager.GetString("ず", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se.
        /// </summary>
        internal static string せ {
            get {
                return ResourceManager.GetString("せ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ze.
        /// </summary>
        internal static string ぜ {
            get {
                return ResourceManager.GetString("ぜ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so.
        /// </summary>
        internal static string そ {
            get {
                return ResourceManager.GetString("そ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zo.
        /// </summary>
        internal static string ぞ {
            get {
                return ResourceManager.GetString("ぞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ta.
        /// </summary>
        internal static string た {
            get {
                return ResourceManager.GetString("た", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        internal static string だ {
            get {
                return ResourceManager.GetString("だ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chi.
        /// </summary>
        internal static string ち {
            get {
                return ResourceManager.GetString("ち", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ji.
        /// </summary>
        internal static string ぢ {
            get {
                return ResourceManager.GetString("ぢ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chi.
        /// </summary>
        internal static string ちぃ {
            get {
                return ResourceManager.GetString("ちぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ji.
        /// </summary>
        internal static string ぢぃ {
            get {
                return ResourceManager.GetString("ぢぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to che.
        /// </summary>
        internal static string ちぇ {
            get {
                return ResourceManager.GetString("ちぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je.
        /// </summary>
        internal static string ぢぇ {
            get {
                return ResourceManager.GetString("ぢぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cha.
        /// </summary>
        internal static string ちゃ {
            get {
                return ResourceManager.GetString("ちゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string ぢゃ {
            get {
                return ResourceManager.GetString("ぢゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chu.
        /// </summary>
        internal static string ちゅ {
            get {
                return ResourceManager.GetString("ちゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ju.
        /// </summary>
        internal static string ぢゅ {
            get {
                return ResourceManager.GetString("ぢゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cho.
        /// </summary>
        internal static string ちょ {
            get {
                return ResourceManager.GetString("ちょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jo.
        /// </summary>
        internal static string ぢょ {
            get {
                return ResourceManager.GetString("ぢょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tsu.
        /// </summary>
        internal static string つ {
            get {
                return ResourceManager.GetString("つ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zu.
        /// </summary>
        internal static string づ {
            get {
                return ResourceManager.GetString("づ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te.
        /// </summary>
        internal static string て {
            get {
                return ResourceManager.GetString("て", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string で {
            get {
                return ResourceManager.GetString("で", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string と {
            get {
                return ResourceManager.GetString("と", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string ど {
            get {
                return ResourceManager.GetString("ど", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to na.
        /// </summary>
        internal static string な {
            get {
                return ResourceManager.GetString("な", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ni.
        /// </summary>
        internal static string に {
            get {
                return ResourceManager.GetString("に", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyi.
        /// </summary>
        internal static string にぃ {
            get {
                return ResourceManager.GetString("にぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nye.
        /// </summary>
        internal static string にぇ {
            get {
                return ResourceManager.GetString("にぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nya.
        /// </summary>
        internal static string にゃ {
            get {
                return ResourceManager.GetString("にゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyu.
        /// </summary>
        internal static string にゅ {
            get {
                return ResourceManager.GetString("にゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyo.
        /// </summary>
        internal static string にょ {
            get {
                return ResourceManager.GetString("にょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu.
        /// </summary>
        internal static string ぬ {
            get {
                return ResourceManager.GetString("ぬ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne.
        /// </summary>
        internal static string ね {
            get {
                return ResourceManager.GetString("ね", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string の {
            get {
                return ResourceManager.GetString("の", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        internal static string は {
            get {
                return ResourceManager.GetString("は", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba.
        /// </summary>
        internal static string ば {
            get {
                return ResourceManager.GetString("ば", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pa.
        /// </summary>
        internal static string ぱ {
            get {
                return ResourceManager.GetString("ぱ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string ひ {
            get {
                return ResourceManager.GetString("ひ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bi.
        /// </summary>
        internal static string び {
            get {
                return ResourceManager.GetString("び", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pi.
        /// </summary>
        internal static string ぴ {
            get {
                return ResourceManager.GetString("ぴ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyi.
        /// </summary>
        internal static string ひぃ {
            get {
                return ResourceManager.GetString("ひぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byi.
        /// </summary>
        internal static string びぃ {
            get {
                return ResourceManager.GetString("びぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pyi.
        /// </summary>
        internal static string ぴぃ {
            get {
                return ResourceManager.GetString("ぴぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hye.
        /// </summary>
        internal static string ひぇ {
            get {
                return ResourceManager.GetString("ひぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bye.
        /// </summary>
        internal static string びぇ {
            get {
                return ResourceManager.GetString("びぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pye.
        /// </summary>
        internal static string ぴぇ {
            get {
                return ResourceManager.GetString("ぴぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hya.
        /// </summary>
        internal static string ひゃ {
            get {
                return ResourceManager.GetString("ひゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bya.
        /// </summary>
        internal static string びゃ {
            get {
                return ResourceManager.GetString("びゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pya.
        /// </summary>
        internal static string ぴゃ {
            get {
                return ResourceManager.GetString("ぴゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyu.
        /// </summary>
        internal static string ひゅ {
            get {
                return ResourceManager.GetString("ひゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byu.
        /// </summary>
        internal static string びゅ {
            get {
                return ResourceManager.GetString("びゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pyu.
        /// </summary>
        internal static string ぴゅ {
            get {
                return ResourceManager.GetString("ぴゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyo.
        /// </summary>
        internal static string ひょ {
            get {
                return ResourceManager.GetString("ひょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byo.
        /// </summary>
        internal static string びょ {
            get {
                return ResourceManager.GetString("びょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pyo.
        /// </summary>
        internal static string ぴょ {
            get {
                return ResourceManager.GetString("ぴょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fu.
        /// </summary>
        internal static string ふ {
            get {
                return ResourceManager.GetString("ふ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bu.
        /// </summary>
        internal static string ぶ {
            get {
                return ResourceManager.GetString("ぶ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pu.
        /// </summary>
        internal static string ぷ {
            get {
                return ResourceManager.GetString("ぷ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        internal static string へ {
            get {
                return ResourceManager.GetString("へ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be.
        /// </summary>
        internal static string べ {
            get {
                return ResourceManager.GetString("べ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pe.
        /// </summary>
        internal static string ぺ {
            get {
                return ResourceManager.GetString("ぺ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ho.
        /// </summary>
        internal static string ほ {
            get {
                return ResourceManager.GetString("ほ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bo.
        /// </summary>
        internal static string ぼ {
            get {
                return ResourceManager.GetString("ぼ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to po.
        /// </summary>
        internal static string ぽ {
            get {
                return ResourceManager.GetString("ぽ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ma.
        /// </summary>
        internal static string ま {
            get {
                return ResourceManager.GetString("ま", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string み {
            get {
                return ResourceManager.GetString("み", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myi.
        /// </summary>
        internal static string みぃ {
            get {
                return ResourceManager.GetString("みぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mye.
        /// </summary>
        internal static string みぇ {
            get {
                return ResourceManager.GetString("みぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mya.
        /// </summary>
        internal static string みゃ {
            get {
                return ResourceManager.GetString("みゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myu.
        /// </summary>
        internal static string みゅ {
            get {
                return ResourceManager.GetString("みゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myo.
        /// </summary>
        internal static string みょ {
            get {
                return ResourceManager.GetString("みょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mu.
        /// </summary>
        internal static string む {
            get {
                return ResourceManager.GetString("む", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        internal static string め {
            get {
                return ResourceManager.GetString("め", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mo.
        /// </summary>
        internal static string も {
            get {
                return ResourceManager.GetString("も", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya.
        /// </summary>
        internal static string や {
            get {
                return ResourceManager.GetString("や", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yu.
        /// </summary>
        internal static string ゆ {
            get {
                return ResourceManager.GetString("ゆ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo.
        /// </summary>
        internal static string よ {
            get {
                return ResourceManager.GetString("よ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ra.
        /// </summary>
        internal static string ら {
            get {
                return ResourceManager.GetString("ら", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ri.
        /// </summary>
        internal static string り {
            get {
                return ResourceManager.GetString("り", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ryi.
        /// </summary>
        internal static string りぃ {
            get {
                return ResourceManager.GetString("りぃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rye.
        /// </summary>
        internal static string りぇ {
            get {
                return ResourceManager.GetString("りぇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rya.
        /// </summary>
        internal static string りゃ {
            get {
                return ResourceManager.GetString("りゃ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ryu.
        /// </summary>
        internal static string りゅ {
            get {
                return ResourceManager.GetString("りゅ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ryo.
        /// </summary>
        internal static string りょ {
            get {
                return ResourceManager.GetString("りょ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        internal static string る {
            get {
                return ResourceManager.GetString("る", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re.
        /// </summary>
        internal static string れ {
            get {
                return ResourceManager.GetString("れ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro.
        /// </summary>
        internal static string ろ {
            get {
                return ResourceManager.GetString("ろ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wa.
        /// </summary>
        internal static string わ {
            get {
                return ResourceManager.GetString("わ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wi.
        /// </summary>
        internal static string ゐ {
            get {
                return ResourceManager.GetString("ゐ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we.
        /// </summary>
        internal static string ゑ {
            get {
                return ResourceManager.GetString("ゑ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wo.
        /// </summary>
        internal static string を {
            get {
                return ResourceManager.GetString("を", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string ん {
            get {
                return ResourceManager.GetString("ん", resourceCulture);
            }
        }
    }
}
