//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaraV2.Tools.LinguistResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RomajiToKatakana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RomajiToKatakana() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanaraV2.Tools.LinguistResources.RomajiToKatakana", typeof(RomajiToKatakana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ド.
        /// </summary>
        internal static string _do {
            get {
                return ResourceManager.GetString("_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ア.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バ.
        /// </summary>
        internal static string ba {
            get {
                return ResourceManager.GetString("ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベ.
        /// </summary>
        internal static string be {
            get {
                return ResourceManager.GetString("be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビ.
        /// </summary>
        internal static string bi {
            get {
                return ResourceManager.GetString("bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボ.
        /// </summary>
        internal static string bo {
            get {
                return ResourceManager.GetString("bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブ.
        /// </summary>
        internal static string bu {
            get {
                return ResourceManager.GetString("bu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビャ.
        /// </summary>
        internal static string bya {
            get {
                return ResourceManager.GetString("bya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビェ.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビィ.
        /// </summary>
        internal static string byi {
            get {
                return ResourceManager.GetString("byi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビョ.
        /// </summary>
        internal static string byo {
            get {
                return ResourceManager.GetString("byo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビュ.
        /// </summary>
        internal static string byu {
            get {
                return ResourceManager.GetString("byu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャ.
        /// </summary>
        internal static string cha {
            get {
                return ResourceManager.GetString("cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェ.
        /// </summary>
        internal static string che {
            get {
                return ResourceManager.GetString("che", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チ.
        /// </summary>
        internal static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チョ.
        /// </summary>
        internal static string cho {
            get {
                return ResourceManager.GetString("cho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チュ.
        /// </summary>
        internal static string chu {
            get {
                return ResourceManager.GetString("chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デ.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジャ.
        /// </summary>
        internal static string dja {
            get {
                return ResourceManager.GetString("dja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジェ.
        /// </summary>
        internal static string dje {
            get {
                return ResourceManager.GetString("dje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジ.
        /// </summary>
        internal static string dji {
            get {
                return ResourceManager.GetString("dji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジョ.
        /// </summary>
        internal static string djo {
            get {
                return ResourceManager.GetString("djo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジュ.
        /// </summary>
        internal static string dju {
            get {
                return ResourceManager.GetString("dju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヂャ.
        /// </summary>
        internal static string dya {
            get {
                return ResourceManager.GetString("dya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヂェ.
        /// </summary>
        internal static string dye {
            get {
                return ResourceManager.GetString("dye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヂィ.
        /// </summary>
        internal static string dyi {
            get {
                return ResourceManager.GetString("dyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヂョ.
        /// </summary>
        internal static string dyo {
            get {
                return ResourceManager.GetString("dyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヂュ.
        /// </summary>
        internal static string dyu {
            get {
                return ResourceManager.GetString("dyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズ.
        /// </summary>
        internal static string dzu {
            get {
                return ResourceManager.GetString("dzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エ.
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フ.
        /// </summary>
        internal static string fu {
            get {
                return ResourceManager.GetString("fu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガ.
        /// </summary>
        internal static string ga {
            get {
                return ResourceManager.GetString("ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲ.
        /// </summary>
        internal static string ge {
            get {
                return ResourceManager.GetString("ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギ.
        /// </summary>
        internal static string gi {
            get {
                return ResourceManager.GetString("gi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゴ.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グ.
        /// </summary>
        internal static string gu {
            get {
                return ResourceManager.GetString("gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギャ.
        /// </summary>
        internal static string gya {
            get {
                return ResourceManager.GetString("gya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギェ.
        /// </summary>
        internal static string gye {
            get {
                return ResourceManager.GetString("gye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギィ.
        /// </summary>
        internal static string gyi {
            get {
                return ResourceManager.GetString("gyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギョ.
        /// </summary>
        internal static string gyo {
            get {
                return ResourceManager.GetString("gyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギュ.
        /// </summary>
        internal static string gyu {
            get {
                return ResourceManager.GetString("gyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハ.
        /// </summary>
        internal static string ha {
            get {
                return ResourceManager.GetString("ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘ.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒ.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホ.
        /// </summary>
        internal static string ho {
            get {
                return ResourceManager.GetString("ho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒャ.
        /// </summary>
        internal static string hya {
            get {
                return ResourceManager.GetString("hya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒェ.
        /// </summary>
        internal static string hye {
            get {
                return ResourceManager.GetString("hye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒィ.
        /// </summary>
        internal static string hyi {
            get {
                return ResourceManager.GetString("hyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒョ.
        /// </summary>
        internal static string hyo {
            get {
                return ResourceManager.GetString("hyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒュ.
        /// </summary>
        internal static string hyu {
            get {
                return ResourceManager.GetString("hyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イ.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジャ.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジェ.
        /// </summary>
        internal static string je {
            get {
                return ResourceManager.GetString("je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジ.
        /// </summary>
        internal static string ji {
            get {
                return ResourceManager.GetString("ji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジョ.
        /// </summary>
        internal static string jo {
            get {
                return ResourceManager.GetString("jo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジュ.
        /// </summary>
        internal static string ju {
            get {
                return ResourceManager.GetString("ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジャ.
        /// </summary>
        internal static string jya {
            get {
                return ResourceManager.GetString("jya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジェ.
        /// </summary>
        internal static string jye {
            get {
                return ResourceManager.GetString("jye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジィ.
        /// </summary>
        internal static string jyi {
            get {
                return ResourceManager.GetString("jyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジョ.
        /// </summary>
        internal static string jyo {
            get {
                return ResourceManager.GetString("jyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジュ.
        /// </summary>
        internal static string jyu {
            get {
                return ResourceManager.GetString("jyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カ.
        /// </summary>
        internal static string ka {
            get {
                return ResourceManager.GetString("ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ケ.
        /// </summary>
        internal static string ke {
            get {
                return ResourceManager.GetString("ke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キ.
        /// </summary>
        internal static string ki {
            get {
                return ResourceManager.GetString("ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コ.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ク.
        /// </summary>
        internal static string ku {
            get {
                return ResourceManager.GetString("ku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャ.
        /// </summary>
        internal static string kya {
            get {
                return ResourceManager.GetString("kya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キェ.
        /// </summary>
        internal static string kye {
            get {
                return ResourceManager.GetString("kye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キィ.
        /// </summary>
        internal static string kyi {
            get {
                return ResourceManager.GetString("kyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジョ.
        /// </summary>
        internal static string kyo {
            get {
                return ResourceManager.GetString("kyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キュ.
        /// </summary>
        internal static string kyu {
            get {
                return ResourceManager.GetString("kyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マ.
        /// </summary>
        internal static string ma {
            get {
                return ResourceManager.GetString("ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メ.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミ.
        /// </summary>
        internal static string mi {
            get {
                return ResourceManager.GetString("mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モ.
        /// </summary>
        internal static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ム.
        /// </summary>
        internal static string mu {
            get {
                return ResourceManager.GetString("mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミャ.
        /// </summary>
        internal static string mya {
            get {
                return ResourceManager.GetString("mya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミェ.
        /// </summary>
        internal static string mye {
            get {
                return ResourceManager.GetString("mye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミィ.
        /// </summary>
        internal static string myi {
            get {
                return ResourceManager.GetString("myi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミョ.
        /// </summary>
        internal static string myo {
            get {
                return ResourceManager.GetString("myo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミュ.
        /// </summary>
        internal static string myu {
            get {
                return ResourceManager.GetString("myu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ン.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナ.
        /// </summary>
        internal static string na {
            get {
                return ResourceManager.GetString("na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネ.
        /// </summary>
        internal static string ne {
            get {
                return ResourceManager.GetString("ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニ.
        /// </summary>
        internal static string ni {
            get {
                return ResourceManager.GetString("ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノ.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヌ.
        /// </summary>
        internal static string nu {
            get {
                return ResourceManager.GetString("nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニャ.
        /// </summary>
        internal static string nya {
            get {
                return ResourceManager.GetString("nya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニェ.
        /// </summary>
        internal static string nye {
            get {
                return ResourceManager.GetString("nye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニィ.
        /// </summary>
        internal static string nyi {
            get {
                return ResourceManager.GetString("nyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニョ.
        /// </summary>
        internal static string nyo {
            get {
                return ResourceManager.GetString("nyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニュ.
        /// </summary>
        internal static string nyu {
            get {
                return ResourceManager.GetString("nyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オ.
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パ.
        /// </summary>
        internal static string pa {
            get {
                return ResourceManager.GetString("pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペ.
        /// </summary>
        internal static string pe {
            get {
                return ResourceManager.GetString("pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピ.
        /// </summary>
        internal static string pi {
            get {
                return ResourceManager.GetString("pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポ.
        /// </summary>
        internal static string po {
            get {
                return ResourceManager.GetString("po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プ.
        /// </summary>
        internal static string pu {
            get {
                return ResourceManager.GetString("pu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピャ.
        /// </summary>
        internal static string pya {
            get {
                return ResourceManager.GetString("pya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピェ.
        /// </summary>
        internal static string pye {
            get {
                return ResourceManager.GetString("pye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピィ.
        /// </summary>
        internal static string pyi {
            get {
                return ResourceManager.GetString("pyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピョ.
        /// </summary>
        internal static string pyo {
            get {
                return ResourceManager.GetString("pyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピュ.
        /// </summary>
        internal static string pyu {
            get {
                return ResourceManager.GetString("pyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラ.
        /// </summary>
        internal static string ra {
            get {
                return ResourceManager.GetString("ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レ.
        /// </summary>
        internal static string re {
            get {
                return ResourceManager.GetString("re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リ.
        /// </summary>
        internal static string ri {
            get {
                return ResourceManager.GetString("ri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロ.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ル.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リャ.
        /// </summary>
        internal static string rya {
            get {
                return ResourceManager.GetString("rya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リェ.
        /// </summary>
        internal static string rye {
            get {
                return ResourceManager.GetString("rye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リィ.
        /// </summary>
        internal static string ryi {
            get {
                return ResourceManager.GetString("ryi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リョ.
        /// </summary>
        internal static string ryo {
            get {
                return ResourceManager.GetString("ryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リュ.
        /// </summary>
        internal static string ryu {
            get {
                return ResourceManager.GetString("ryu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サ.
        /// </summary>
        internal static string sa {
            get {
                return ResourceManager.GetString("sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セ.
        /// </summary>
        internal static string se {
            get {
                return ResourceManager.GetString("se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シャ.
        /// </summary>
        internal static string sha {
            get {
                return ResourceManager.GetString("sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シェ.
        /// </summary>
        internal static string she {
            get {
                return ResourceManager.GetString("she", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シ.
        /// </summary>
        internal static string shi {
            get {
                return ResourceManager.GetString("shi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ショ.
        /// </summary>
        internal static string sho {
            get {
                return ResourceManager.GetString("sho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シュ.
        /// </summary>
        internal static string shu {
            get {
                return ResourceManager.GetString("shu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソ.
        /// </summary>
        internal static string so {
            get {
                return ResourceManager.GetString("so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ス.
        /// </summary>
        internal static string su {
            get {
                return ResourceManager.GetString("su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タ.
        /// </summary>
        internal static string ta {
            get {
                return ResourceManager.GetString("ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テ.
        /// </summary>
        internal static string te {
            get {
                return ResourceManager.GetString("te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ト.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツ.
        /// </summary>
        internal static string tsu {
            get {
                return ResourceManager.GetString("tsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャ.
        /// </summary>
        internal static string tya {
            get {
                return ResourceManager.GetString("tya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェ.
        /// </summary>
        internal static string tye {
            get {
                return ResourceManager.GetString("tye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チィ.
        /// </summary>
        internal static string tyi {
            get {
                return ResourceManager.GetString("tyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チョ.
        /// </summary>
        internal static string tyo {
            get {
                return ResourceManager.GetString("tyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チュ.
        /// </summary>
        internal static string tyu {
            get {
                return ResourceManager.GetString("tyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウ.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヴァ.
        /// </summary>
        internal static string va {
            get {
                return ResourceManager.GetString("va", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヴェ.
        /// </summary>
        internal static string ve {
            get {
                return ResourceManager.GetString("ve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヴィ.
        /// </summary>
        internal static string vi {
            get {
                return ResourceManager.GetString("vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヴォ.
        /// </summary>
        internal static string vo {
            get {
                return ResourceManager.GetString("vo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヴ.
        /// </summary>
        internal static string vu {
            get {
                return ResourceManager.GetString("vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワ.
        /// </summary>
        internal static string wa {
            get {
                return ResourceManager.GetString("wa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェ.
        /// </summary>
        internal static string we {
            get {
                return ResourceManager.GetString("we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィ.
        /// </summary>
        internal static string wi {
            get {
                return ResourceManager.GetString("wi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヲ.
        /// </summary>
        internal static string wo {
            get {
                return ResourceManager.GetString("wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヤ.
        /// </summary>
        internal static string ya {
            get {
                return ResourceManager.GetString("ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヨ.
        /// </summary>
        internal static string yo {
            get {
                return ResourceManager.GetString("yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユ.
        /// </summary>
        internal static string yu {
            get {
                return ResourceManager.GetString("yu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ザ.
        /// </summary>
        internal static string za {
            get {
                return ResourceManager.GetString("za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゼ.
        /// </summary>
        internal static string ze {
            get {
                return ResourceManager.GetString("ze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゾ.
        /// </summary>
        internal static string zo {
            get {
                return ResourceManager.GetString("zo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズ.
        /// </summary>
        internal static string zu {
            get {
                return ResourceManager.GetString("zu", resourceCulture);
            }
        }
    }
}
